#!/usr/bin/env bash

set -o errexit -o nounset

commit_message_file="$1"
commit_source="${2-}"

if [[ -n $commit_source ]]
then
    # Not opening an editor
    exit 0
fi

cleanup() {
    rm -rf "$working_directory"
}
trap cleanup EXIT
working_directory="$(mktemp -d)"
temporary_file="${working_directory}/message"

branch_name="$(git rev-parse --abbrev-ref HEAD)"
request_prefix="${branch_name%%-*}"

echo "${request_prefix}: " | cat - "$commit_message_file" > "$temporary_file"
mv "$temporary_file" "$commit_message_file"
