# Generated by Django 5.2.8 on 2026-01-11 07:06

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Unique identifier (e.g., 'privacy-policy', 'terms-of-service')", max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable name displayed to users', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Internal description for administrators')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Terms',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='TermVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text="Version identifier (e.g., '1.0', '2.1', '2024-01-15'). This is for reference only - the 'latest' version is determined by the most recent activation date, not this version number.", max_length=50)),
                ('content', wagtail.fields.RichTextField(help_text='The full legal text users must accept')),
                ('change_log', wagtail.fields.RichTextField(blank=True, help_text='Summary of changes from previous version (for internal use)')),
                ('is_active', models.BooleanField(default=False, help_text='Draft versions should be inactive. Activate when ready to enforce.')),
                ('date_active', models.DateTimeField(help_text="Version becomes enforceable from this date/time. The version with the most recent activation date is considered the 'latest' version that users must accept, regardless of version number.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='terms.term')),
            ],
            options={
                'verbose_name': 'Term Version',
                'verbose_name_plural': 'Term Versions',
                'ordering': ['-date_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TermAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address from which acceptance was recorded')),
                ('user_agent', models.TextField(help_text='Browser user agent string')),
                ('source', models.CharField(default='web', help_text="Source of acceptance (e.g., 'web', 'api', 'sso')", max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_acceptances', to=settings.AUTH_USER_MODEL)),
                ('term_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='terms.termversion')),
            ],
            options={
                'verbose_name': 'Term Acceptance',
                'verbose_name_plural': 'Term Acceptances',
                'ordering': ['-accepted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='termversion',
            index=models.Index(fields=['is_active', 'date_active'], name='terms_termv_is_acti_51aa96_idx'),
        ),
        migrations.AddConstraint(
            model_name='termversion',
            constraint=models.UniqueConstraint(fields=('term', 'version'), name='unique_term_version'),
        ),
        migrations.AddIndex(
            model_name='termacceptance',
            index=models.Index(fields=['user', 'accepted_at'], name='terms_terma_user_id_405f08_idx'),
        ),
        migrations.AddConstraint(
            model_name='termacceptance',
            constraint=models.UniqueConstraint(fields=('user', 'term_version'), name='unique_user_term_version_acceptance'),
        ),
    ]
