# Generated by Django 5.2.15 on 2026-06-22 01:25

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='name_en',
            field=models.CharField(help_text='Human-readable name displayed to users', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='name_mi',
            field=models.CharField(help_text='Human-readable name displayed to users', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='termversion',
            name='content_en',
            field=wagtail.fields.RichTextField(help_text='The full legal text users must accept', null=True),
        ),
        migrations.AddField(
            model_name='termversion',
            name='content_mi',
            field=wagtail.fields.RichTextField(help_text='The full legal text users must accept', null=True),
        ),
    ]
