# Generated by Django 5.2.11 on 2026-03-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Custom sort order. When 0 (unset), falls back to alphabetical sort.'),
        ),
    ]
