# Generated by Django 5.2.15 on 2026-06-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_region_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Custom sort order. When 0, falls back to alphabetical sort.'),
        ),
    ]
