# Generated by Django 5.2.15 on 2026-06-22 01:25

import autoslug.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_region_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_mi',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='name_mi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='description_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='description_mi',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='name_en',
            field=models.CharField(help_text='Name of location, for example: Middleton Grange School', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='name_mi',
            field=models.CharField(help_text='Name of location, for example: Middleton Grange School', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name_mi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='abbreviation_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='abbreviation_mi',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='description_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='description_mi',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='name_mi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='description_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='description_mi',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='name_mi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='_slug_source'),
        ),
    ]
