# Generated by Django 4.2.2 on 2023-07-03 04:06

import relativedeltafield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("base", "0003_create_membershippage")]

    operations = [
        migrations.CreateModel(
            name="MembershipOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("INDIVIDUAL", "Individual"), ("ORGANISATION", "Organisation")], max_length=255
                    ),
                ),
                ("duration", relativedeltafield.fields.RelativeDeltaField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
