# Generated by Django 4.2.3 on 2023-08-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_add_user_membership"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
