# Generated by Django 4.2.3 on 2023-08-21 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_add_organisation_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("postal_address", models.TextField(blank=True)),
                ("office_phone", models.CharField(blank=True, max_length=255)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organisations",
                        to="users.organisationtype",
                    ),
                ),
            ],
        ),
    ]
