# Generated by Django 4.2.5 on 2023-09-18 04:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_add_organisation"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermembership",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.localdate),
            preserve_default=False,
        ),
    ]
