# Generated by Django 4.2.5 on 2023-09-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_add_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermembership",
            name="cancelled_datetime",
            field=models.DateTimeField(null=True),
        ),
    ]
