# Generated by Django 4.2.7 on 2023-11-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_add_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="office_phone",
            field=models.CharField(blank=False, max_length=255),
        ),
        migrations.RenameField(
            model_name="organisation",
            old_name="office_phone",
            new_name="telephone",
        ),
        migrations.AddField(
            model_name="organisation",
            name="contact_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organisation",
            name="email",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organisation",
            name="postal_address",
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name="organisation",
            name="postal_city",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organisation",
            name="postal_suburb",
            field=models.CharField(blank=True, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organisation",
            name="postal_code",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organisation",
            name="street_address",
            field=models.CharField(blank=True, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organisation",
            name="suburb",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="organisation",
            name="city",
            field=models.CharField(blank=True, max_length=255),
            preserve_default=False,
        ),
    ]
