# Generated by Django 4.2.7 on 2023-11-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_organisation_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationmember",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
