# Generated by Django 4.2.7 on 2023-12-03 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_organisation_member_is_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField()),
                ("created_datetime", models.DateTimeField()),
                ("cancelled_datetime", models.DateTimeField(null=True)),
                (
                    "membership_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organisation_memberships",
                        to="users.membershipoption",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organisation_memberships",
                        to="users.organisation",
                    ),
                ),
            ],
        ),
    ]
