# Generated by Django 4.2.7 on 2024-02-22 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_invoice_billing_service_invoice_id"),
        ("users", "0011_add_organisation_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationmembership",
            name="invoice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organisation_memberships",
                to="billing.invoice",
            ),
        ),
        migrations.AddField(
            model_name="usermembership",
            name="invoice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_memberships",
                to="billing.invoice",
            ),
        ),
    ]
