# Generated by Django 4.2.7 on 2024-03-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_membership_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipoption",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="organisationmember",
            name="invite_token",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="membershipoption",
            unique_together={("name", "type")},
        ),
    ]
