# Generated by Django 4.2.7 on 2024-02-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("xero", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="XeroMutex",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
    ]
