from os import environ
from pathlib import Path
from typing import Any, Dict, Iterable, Optional

import django.conf.locale
import sentry_sdk
from configurations import Configuration
from sentry_sdk.integrations.django import DjangoIntegration


class Common(Configuration):
    @classmethod
    def setup(cls) -> None:
        super().setup()

        dsn: Optional[str] = environ.get("SENTRY_DSN")
        if dsn == "":
            dsn = None
        sentry_sdk.init(
            dsn=dsn,
            release=environ.get("APPLICATION_VERSION"),
            server_name=environ["APPLICATION_WEB_HOST"],
            integrations=[DjangoIntegration()],
            send_default_pii=True,
        )

        # Add additional language info not built into django.conf.locale
        django.conf.locale.LANG_INFO = dict(django.conf.locale.LANG_INFO, **cls.EXTRA_LANG_INFO)

    # Build paths inside the project like this: BASE_DIR / 'subdir'.
    BASE_DIR = Path(__file__).resolve().parent.parent

    # SECURITY WARNING: don't run with debug turned on in production!
    SECRET_KEY = environ["DJANGO_SECRET_KEY"]

    DEBUG = False

    ALLOWED_HOSTS: Iterable[str] = ["backend", environ["APPLICATION_WEB_HOST"]]

    # Application definition

    INSTALLED_APPS = [
        "ams.base",
        "ams.users",
        "ams.forum",
        "registration",
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
        "django.contrib.staticfiles",
        "wagtail.contrib.forms",
        "wagtail.contrib.redirects",
        "wagtail.contrib.simple_translation",
        "wagtail.contrib.modeladmin",
        "wagtailmenus",
        "wagtail.embeds",
        "wagtail.sites",
        "wagtail.users",
        "wagtail.snippets",
        "wagtail.documents",
        "wagtail.images",
        "wagtail.search",
        "wagtail.admin",
        "wagtail.locales",
        "wagtail",
        "modelcluster",
        "taggit",
        "django_tables2",
    ]

    MIDDLEWARE = [
        "django.middleware.locale.LocaleMiddleware",
        "django.middleware.security.SecurityMiddleware",
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.middleware.common.CommonMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
        "wagtail.contrib.redirects.middleware.RedirectMiddleware",
    ]

    ROOT_URLCONF = "ams.urls"

    TEMPLATES = [
        {
            "BACKEND": "django.template.backends.django.DjangoTemplates",
            "DIRS": [],
            "APP_DIRS": True,
            "OPTIONS": {
                "context_processors": [
                    "django.template.context_processors.debug",
                    "django.template.context_processors.request",
                    "django.contrib.auth.context_processors.auth",
                    "django.contrib.messages.context_processors.messages",
                    "wagtailmenus.context_processors.wagtailmenus",
                ],
            },
        },
    ]

    WSGI_APPLICATION = "ams.wsgi.application"

    # Database
    # https://docs.djangoproject.com/en/4.2/ref/settings/#databases

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": environ["APPLICATION_DB_NAME"],
            "USER": environ["APPLICATION_DB_USER"],
            "HOST": environ["APPLICATION_DB_HOST"],
            "PASSWORD": environ["APPLICATION_DB_PASSWORD"],
            "PORT": 5432,
            "OPTIONS": {"connect_timeout": 5},
            "ATOMIC_REQUESTS": True,
        }
    }

    # Discourse integration
    DISCOURSE_API_KEY = environ["DISCOURSE_API_KEY"]
    DISCOURSE_API_USERNAME = environ["DISCOURSE_API_USERNAME"]
    DISCOURSE_REDIRECT_DOMAIN = environ["DISCOURSE_REDIRECT_DOMAIN"]
    DISCOURSE_CONNECT_SECRET = environ["DISCOURSE_CONNECT_SECRET"]

    # Password validation
    # https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

    AUTH_PASSWORD_VALIDATORS = [
        {
            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        },
    ]

    # Internationalization
    # https://docs.djangoproject.com/en/4.2/topics/i18n/

    LANGUAGE_CODE = "en"

    USE_I18N = True

    USE_TZ = True

    USE_L10N = False

    LOCALE_PATHS = [BASE_DIR / "locale"]

    # Silence warning generated by wagtailmenus
    # Should be fixed in next release: https://github.com/jazzband/wagtailmenus/pull/441
    # https://docs.djangoproject.com/en/4.2/ref/settings/#silenced-system-checks

    SILENCED_SYSTEM_CHECKS = ["wagtailadmin.W002"]

    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/4.2/howto/static-files/
    # TODO: probably should serve static files from Nginx

    STATIC_URL = "static/"
    STATIC_ROOT = BASE_DIR / "static"

    # User uploaded files
    # https://docs.djangoproject.com/en/4.2/topics/files/
    # TODO: need solution production solution for user uploaded files

    MEDIA_URL = "media/"
    MEDIA_ROOT = BASE_DIR / "media"

    # Email
    # https://docs.djangoproject.com/en/4.2/topics/email/

    EMAIL_HOST = environ["EMAIL_HOST"]
    EMAIL_HOST_USER = environ.get("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = environ.get("EMAIL_HOST_PASSWORD", "")
    DEFAULT_FROM_EMAIL = environ.get("DEFAULT_FROM_EMAIL", "webmaster@localhost")

    # Wagtail settings
    # https://docs.wagtail.org/en/stable/reference/settings.html

    WAGTAIL_SITE_NAME = "Association Management Software"
    WAGTAILADMIN_BASE_URL = environ["APPLICATION_WEB_HOST"] + "/cms"
    WAGTAIL_I18N_ENABLED = True
    WAGTAIL_CONTENT_LANGUAGES = LANGUAGES = [("en", "English")]

    EXTRA_LANG_INFO: Dict[str, Any] = {}

    WAGTAILSIMPLETRANSLATION_SYNC_PAGE_TREE = True

    # Django registration redux
    # https://django-registration-redux.readthedocs.io/en/latest/quickstart.html

    ACCOUNT_ACTIVATION_DAYS = 7
    REGISTRATION_AUTO_LOGIN = False
    REGISTRATION_EMAIL_HTML = False
    LOGIN_REDIRECT_URL = "/"
    LOGOUT_REDIRECT_URL = "/"
    LOGIN_URL = "/users/login/"

    # Django tables 2
    # https://django-tables2.readthedocs.io/en/latest/pages/

    DJANGO_TABLES2_TABLE_ATTRS = {
        "class": "table table-striped table-bordered table-sm",
    }

    # Default primary key field type
    # https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

    DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


class Development(Common):
    DEBUG = True
    CSRF_TRUSTED_ORIGINS = ["http://" + environ["APPLICATION_WEB_HOST"] + ":1800"]


class Testing(Common):
    DEBUG = False
    CSRF_TRUSTED_ORIGINS = ["https://" + environ["APPLICATION_WEB_HOST"]]
