# Generated by Django 5.2.5 on 2025-09-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association_short_name', models.CharField(blank=True, max_length=255, verbose_name='Association short name')),
                ('association_long_name', models.CharField(blank=True, max_length=255, verbose_name='Association long name')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
