# Generated by Django 5.2.5 on 2025-09-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_associationsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='lead_paragraph',
        ),
    ]
