# Generated by Django 5.2.5 on 2025-09-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_aboutpage_associationsettings_association_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationsettings',
            name='use_logo_in_navbar',
            field=models.BooleanField(default=False, help_text='If not set, the association short name will be used in the navbar.', verbose_name='Use logo in navbar'),
        ),
    ]
