# Generated by Django 5.2.5 on 2025-09-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_associationsettings_use_logo_in_navbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationsettings',
            name='use_logo_in_footer',
            field=models.BooleanField(default=False, help_text='If not set, the association short name will be used in the navbar.', verbose_name='Use logo in footer'),
        ),
        migrations.AlterField(
            model_name='associationsettings',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='If set, a link will appear in the footer.', verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='associationsettings',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='If set, a link will appear in the footer.', verbose_name='LinkedIn URL'),
        ),
    ]
