# Generated by Django 5.2.5 on 2025-09-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_associationsettings_use_logo_in_footer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationsettings',
            name='use_logo_in_footer',
            field=models.BooleanField(default=False, help_text='If not set, the association short name will be used in the footer.', verbose_name='Use logo in footer'),
        ),
    ]
