# Generated by Django 5.2.5 on 2025-09-29 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_alter_aboutpage_body'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutPage',
            new_name='ContentPage',
        ),
    ]
