# Generated by Django 5.2.5 on 2025-11-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_contentpage_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('members', 'Members only')], default='public', help_text=('Who can view this page: everyone or only members with active membership.',), max_length=16),
        ),
    ]
