# Generated by Django 5.2.5 on 2025-11-16 07:33

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_amsdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amsdocument',
            name='file',
            field=models.FileField(storage=config.storage_backends.PrivateMediaStorage(access_key='minioadmin', bucket_name='ams-media-private', custom_domain='localhost:9000/ams-media-private', endpoint_url='http://minio:9000', region_name=None, secret_key='minioadminpassword'), upload_to='documents', verbose_name='file'),
        ),
    ]
