# Generated by Django 5.2.5 on 2025-11-16 08:43

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_alter_amsdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.fields.StreamField([('heading_block', 2), ('paragraph_block', 3), ('image_block', 6), ('embed_block', 7), ('columns_block', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a heading size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 4: ('wagtail.images.blocks.ImageBlock', [], {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('attribution', 5)]], {}), 7: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Insert a URL to embed. For example, https://www.youtube.com/watch?v=V-6m0jW0X9E', 'icon': 'media'}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2-equal', '2 Columns (Equal)'), ('3-equal', '3 Columns (Equal)'), ('4-equal', '4 Columns (Equal)'), ('2-thirds-1-third', '2 Columns (2/3 + 1/3)'), ('1-third-2-thirds', '2 Columns (1/3 + 2/3)')], 'help_text': 'Select the column layout'}), 9: ('wagtail.blocks.StreamBlock', [[('heading_block', 2), ('paragraph_block', 3), ('image_block', 6), ('embed_block', 7)]], {'help_text': 'Content for the first column', 'required': False}), 10: ('wagtail.blocks.StreamBlock', [[('heading_block', 2), ('paragraph_block', 3), ('image_block', 6), ('embed_block', 7)]], {'help_text': 'Content for the second column', 'required': False}), 11: ('wagtail.blocks.StreamBlock', [[('heading_block', 2), ('paragraph_block', 3), ('image_block', 6), ('embed_block', 7)]], {'help_text': 'Content for the third column (only used in 3 or 4 column layouts)', 'required': False}), 12: ('wagtail.blocks.StreamBlock', [[('heading_block', 2), ('paragraph_block', 3), ('image_block', 6), ('embed_block', 7)]], {'help_text': 'Content for the fourth column (only used in 4 column layout)', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('layout', 8), ('column_1', 9), ('column_2', 10), ('column_3', 11), ('column_4', 12)]], {})}, help_text='Content for the about page.'),
        ),
    ]
