# Generated by Django 5.2.5 on 2025-11-17 08:28

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_alter_contentpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.fields.StreamField([('heading_block', 2), ('paragraph_block', 3), ('image_block', 6), ('embed_block', 7), ('columns_block', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a heading size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 4: ('wagtail.images.blocks.ImageBlock', [], {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('attribution', 5)]], {}), 7: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Insert a URL to embed. For example, https://www.youtube.com/watch?v=V-6m0jW0X9E', 'icon': 'media'}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2-equal', '2 Columns (Equal)'), ('3-equal', '3 Columns (Equal)'), ('4-equal', '4 Columns (Equal)'), ('2-thirds-1-third', '2 Columns (2/3 + 1/3)'), ('1-third-2-thirds', '2 Columns (1/3 + 2/3)')], 'help_text': 'Select the column layout, then add the appropriate number of columns below.'}), 9: ('wagtail.blocks.StreamBlock', [[('heading_block', 2), ('paragraph_block', 3), ('image_block', 6), ('embed_block', 7)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'help_text': 'Add columns here. Number of columns should match your layout choice.', 'max_num': 4, 'min_num': 2}), 11: ('wagtail.blocks.StructBlock', [[('layout', 8), ('columns', 10)]], {})}, help_text='Content for the about page.'),
        ),
    ]
