# Generated by Django 5.2.8 on 2025-11-30 07:19

import django.db.models.deletion
from django.db import migrations, models


def set_default_site(apps, schema_editor):
    """Set the site field to the first available site."""
    AssociationSettings = apps.get_model('cms', 'AssociationSettings')
    Site = apps.get_model('wagtailcore', 'Site')

    # Get the first site, ordered by ID
    first_site = Site.objects.order_by('id').first()

    if first_site:
        # Update all existing AssociationSettings records
        AssociationSettings.objects.filter(site__isnull=True).update(site=first_site)


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_alter_contentpage_body'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        # Step 1: Add the field as nullable
        migrations.AddField(
            model_name='associationsettings',
            name='site',
            field=models.OneToOneField(
                null=True,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to='wagtailcore.site'
            ),
        ),
        # Step 2: Populate with the first available site
        migrations.RunPython(set_default_site, reverse_code=migrations.RunPython.noop),
        # Step 3: Make the field non-nullable
        migrations.AlterField(
            model_name='associationsettings',
            name='site',
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to='wagtailcore.site'
            ),
        ),
        # Create the SiteSettings model with site field as OneToOneField
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('mi', 'Te Reo Māori')], max_length=10, verbose_name='Language')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
