# Generated by Django 5.2.8 on 2025-12-16 09:08

import ams.cms.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_associationsettings_site_sitesettings'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css_version', models.IntegerField(default=1, editable=False, help_text='Auto-incremented on save to invalidate cached CSS')),
                ('primary_color', models.CharField(default='#0d6efd', help_text='Primary brand color', max_length=7, validators=[ams.cms.validators.validate_hex_color])),
                ('secondary_color', models.CharField(default='#6c757d', help_text='Secondary brand color', max_length=7, validators=[ams.cms.validators.validate_hex_color])),
                ('success_color', models.CharField(default='#198754', help_text='Success/positive action color', max_length=7, validators=[ams.cms.validators.validate_hex_color])),
                ('info_color', models.CharField(default='#0dcaf0', help_text='Informational color', max_length=7, validators=[ams.cms.validators.validate_hex_color])),
                ('warning_color', models.CharField(default='#ffc107', help_text='Warning/caution color', max_length=7, validators=[ams.cms.validators.validate_hex_color])),
                ('danger_color', models.CharField(default='#dc3545', help_text='Danger/error color', max_length=7, validators=[ams.cms.validators.validate_hex_color])),
                ('light_color', models.CharField(default='#f8f9fa', help_text='Light color for backgrounds', max_length=7, validators=[ams.cms.validators.validate_hex_color])),
                ('dark_color', models.CharField(default='#212529', help_text='Dark color for text', max_length=7, validators=[ams.cms.validators.validate_hex_color])),
                ('body_bg_light', models.CharField(default='#ffffff', help_text='Light mode: Page background color', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Body background (light)')),
                ('body_color_light', models.CharField(default='#212529', help_text='Light mode: Main text color', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Body text color (light)')),
                ('body_bg_dark', models.CharField(default='#212529', help_text='Dark mode: Page background color', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Body background (dark)')),
                ('body_color_dark', models.CharField(default='#dee2e6', help_text='Dark mode: Main text color', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Body text color (dark)')),
                ('link_color_light', models.CharField(default='#0d6efd', help_text='Light mode: Hyperlink color', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Link color (light)')),
                ('link_hover_color_light', models.CharField(default='#0a58ca', help_text='Light mode: Hyperlink hover color', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Link hover color (light)')),
                ('link_color_dark', models.CharField(default='#6ea8fe', help_text='Dark mode: Hyperlink color', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Link color (dark)')),
                ('link_hover_color_dark', models.CharField(default='#8bb9fe', help_text='Dark mode: Hyperlink hover color', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Link hover color (dark)')),
                ('border_color_light', models.CharField(default='#dee2e6', help_text='Light mode: Default border color', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Border color (light)')),
                ('border_color_dark', models.CharField(default='#495057', help_text='Dark mode: Default border color', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Border color (dark)')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Theme Settings',
            },
        ),
    ]
