# Generated by Django 5.2.8 on 2025-12-17 06:00

import ams.cms.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_add_theme_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themesettings',
            name='secondary_color',
        ),
        migrations.AddField(
            model_name='themesettings',
            name='danger_bg_subtle_dark',
            field=models.CharField(default='#2c0b0e', help_text='Dark mode: Subtle danger background', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Danger subtle background (dark)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='danger_bg_subtle_light',
            field=models.CharField(default='#f8d7da', help_text='Light mode: Subtle danger background', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Danger subtle background (light)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='danger_border_subtle_dark',
            field=models.CharField(default='#842029', help_text='Dark mode: Subtle danger border', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Danger subtle border (dark)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='danger_border_subtle_light',
            field=models.CharField(default='#f1aeb5', help_text='Light mode: Subtle danger border', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Danger subtle border (light)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='danger_text_emphasis_dark',
            field=models.CharField(default='#ea868f', help_text='Dark mode: Emphasized danger text', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Danger text emphasis (dark)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='danger_text_emphasis_light',
            field=models.CharField(default='#58151c', help_text='Light mode: Emphasized danger text', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Danger text emphasis (light)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='dark_bg_subtle_dark',
            field=models.CharField(default='#1a1d20', help_text='Dark mode: Subtle dark background', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Dark subtle background (dark)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='dark_bg_subtle_light',
            field=models.CharField(default='#ced4da', help_text='Light mode: Subtle dark background', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Dark subtle background (light)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='dark_border_subtle_dark',
            field=models.CharField(default='#343a40', help_text='Dark mode: Subtle dark border', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Dark subtle border (dark)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='dark_border_subtle_light',
            field=models.CharField(default='#adb5bd', help_text='Light mode: Subtle dark border', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Dark subtle border (light)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='dark_text_emphasis_dark',
            field=models.CharField(default='#dee2e6', help_text='Dark mode: Emphasized dark text', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Dark text emphasis (dark)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='dark_text_emphasis_light',
            field=models.CharField(default='#495057', help_text='Light mode: Emphasized dark text', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Dark text emphasis (light)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='emphasis_color_dark',
            field=models.CharField(default='#ffffff', help_text='Dark mode: For higher contrast text', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Emphasis color (dark)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='emphasis_color_light',
            field=models.CharField(default='#000000', help_text='Light mode: For higher contrast text', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Emphasis color (light)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='info_bg_subtle_dark',
            field=models.CharField(default='#032830', help_text='Dark mode: Subtle info background', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Info subtle background (dark)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='info_bg_subtle_light',
            field=models.CharField(default='#cff4fc', help_text='Light mode: Subtle info background', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Info subtle background (light)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='info_border_subtle_dark',
            field=models.CharField(default='#087990', help_text='Dark mode: Subtle info border', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Info subtle border (dark)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='info_border_subtle_light',
            field=models.CharField(default='#9eeaf9', help_text='Light mode: Subtle info border', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Info subtle border (light)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='info_text_emphasis_dark',
            field=models.CharField(default='#6edff6', help_text='Dark mode: Emphasized info text', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Info text emphasis (dark)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='info_text_emphasis_light',
            field=models.CharField(default='#055160', help_text='Light mode: Emphasized info text', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Info text emphasis (light)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='light_bg_subtle_dark',
            field=models.CharField(default='#343a40', help_text='Dark mode: Subtle light background', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Light subtle background (dark)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='light_bg_subtle_light',
            field=models.CharField(default='#fcfcfd', help_text='Light mode: Subtle light background', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Light subtle background (light)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='light_border_subtle_dark',
            field=models.CharField(default='#495057', help_text='Dark mode: Subtle light border', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Light subtle border (dark)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='light_border_subtle_light',
            field=models.CharField(default='#e9ecef', help_text='Light mode: Subtle light border', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Light subtle border (light)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='light_text_emphasis_dark',
            field=models.CharField(default='#f8f9fa', help_text='Dark mode: Emphasized light text', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Light text emphasis (dark)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='light_text_emphasis_light',
            field=models.CharField(default='#495057', help_text='Light mode: Emphasized light text', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Light text emphasis (light)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='primary_bg_subtle_dark',
            field=models.CharField(default='#031633', help_text='Dark mode: Subtle primary background', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Primary subtle background (dark)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='primary_bg_subtle_light',
            field=models.CharField(default='#cfe2ff', help_text='Light mode: Subtle primary background', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Primary subtle background (light)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='primary_border_subtle_dark',
            field=models.CharField(default='#084298', help_text='Dark mode: Subtle primary border', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Primary subtle border (dark)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='primary_border_subtle_light',
            field=models.CharField(default='#9ec5fe', help_text='Light mode: Subtle primary border', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Primary subtle border (light)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='primary_text_emphasis_dark',
            field=models.CharField(default='#6ea8fe', help_text='Dark mode: Emphasized primary text', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Primary text emphasis (dark)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='primary_text_emphasis_light',
            field=models.CharField(default='#052c65', help_text='Light mode: Emphasized primary text', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Primary text emphasis (light)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='secondary_bg_dark',
            field=models.CharField(default='#343a40', help_text='Dark mode: For dividers and disabled states', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Secondary background (dark)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='secondary_bg_light',
            field=models.CharField(default='#e9ecef', help_text='Light mode: For dividers and disabled states', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Secondary background (light)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='secondary_color_dark',
            field=models.CharField(default='#dee2e6', help_text='Dark mode: Lighter text color option', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Secondary text (dark)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='secondary_color_light',
            field=models.CharField(default='#6c757d', help_text='Light mode: Lighter text color option', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Secondary text (light)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='success_bg_subtle_dark',
            field=models.CharField(default='#051b11', help_text='Dark mode: Subtle success background', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Success subtle background (dark)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='success_bg_subtle_light',
            field=models.CharField(default='#d1e7dd', help_text='Light mode: Subtle success background', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Success subtle background (light)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='success_border_subtle_dark',
            field=models.CharField(default='#0f5132', help_text='Dark mode: Subtle success border', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Success subtle border (dark)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='success_border_subtle_light',
            field=models.CharField(default='#a3cfbb', help_text='Light mode: Subtle success border', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Success subtle border (light)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='success_text_emphasis_dark',
            field=models.CharField(default='#75b798', help_text='Dark mode: Emphasized success text', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Success text emphasis (dark)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='success_text_emphasis_light',
            field=models.CharField(default='#0a3622', help_text='Light mode: Emphasized success text', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Success text emphasis (light)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='tertiary_bg_dark',
            field=models.CharField(default='#2b3035', help_text='Dark mode: For hover states, accents, and wells', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Tertiary background (dark)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='tertiary_bg_light',
            field=models.CharField(default='#f8f9fa', help_text='Light mode: For hover states, accents, and wells', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Tertiary background (light)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='tertiary_color_dark',
            field=models.CharField(default='#dee2e6', help_text='Dark mode: Even lighter text color option', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Tertiary text (dark)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='tertiary_color_light',
            field=models.CharField(default='#6c757d', help_text='Light mode: Even lighter text color option', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Tertiary text (light)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='warning_bg_subtle_dark',
            field=models.CharField(default='#332701', help_text='Dark mode: Subtle warning background', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Warning subtle background (dark)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='warning_bg_subtle_light',
            field=models.CharField(default='#fff3cd', help_text='Light mode: Subtle warning background', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Warning subtle background (light)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='warning_border_subtle_dark',
            field=models.CharField(default='#997404', help_text='Dark mode: Subtle warning border', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Warning subtle border (dark)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='warning_border_subtle_light',
            field=models.CharField(default='#ffe69c', help_text='Light mode: Subtle warning border', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Warning subtle border (light)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='warning_text_emphasis_dark',
            field=models.CharField(default='#ffda6a', help_text='Dark mode: Emphasized warning text', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Warning text emphasis (dark)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='warning_text_emphasis_light',
            field=models.CharField(default='#664d03', help_text='Light mode: Emphasized warning text', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Warning text emphasis (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='body_bg_dark',
            field=models.CharField(default='#212529', help_text='Dark mode: Default background for body', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Body background (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='body_bg_light',
            field=models.CharField(default='#ffffff', help_text='Light mode: Default background for body', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Body background (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='body_color_dark',
            field=models.CharField(default='#dee2e6', help_text='Dark mode: Default foreground color for text', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Body text color (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='body_color_light',
            field=models.CharField(default='#212529', help_text='Light mode: Default foreground color for text', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Body text color (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='border_color_dark',
            field=models.CharField(default='#495057', help_text='Dark mode: For component borders, dividers, and rules', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Border color (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='border_color_light',
            field=models.CharField(default='#dee2e6', help_text='Light mode: For component borders, dividers, and rules', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Border color (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='danger_color',
            field=models.CharField(default='#dc3545', help_text='Theme color for errors and dangerous actions', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Danger'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='dark_color',
            field=models.CharField(default='#212529', help_text='Additional theme option for higher contrasting colors', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Dark'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='info_color',
            field=models.CharField(default='#0dcaf0', help_text='Theme color for neutral and informative content', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Info'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='light_color',
            field=models.CharField(default='#f8f9fa', help_text='Additional theme option for less contrasting colors', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Light'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='link_color_dark',
            field=models.CharField(default='#6ea8fe', help_text='Dark mode: Default hyperlink color', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Link color (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='link_color_light',
            field=models.CharField(default='#0d6efd', help_text='Light mode: Default hyperlink color', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Link color (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='primary_color',
            field=models.CharField(default='#0d6efd', help_text='Main theme color for hyperlinks, focus styles, and active states', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Primary'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='success_color',
            field=models.CharField(default='#198754', help_text='Theme color for positive or successful actions', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Success'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='warning_color',
            field=models.CharField(default='#ffc107', help_text='Theme color for non-destructive warning messages', max_length=7, validators=[ams.cms.validators.validate_hex_color], verbose_name='Warning'),
        ),
    ]
