# Generated by Django 5.2.8 on 2025-12-18 09:12

import wagtail_color_panel.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_themesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesettings',
            name='body_bg_dark',
            field=wagtail_color_panel.fields.ColorField(default='#212529', help_text='Dark mode: Default background for body.<br>Default: <code>#212529</code>', max_length=7, verbose_name='Body background (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='body_bg_light',
            field=wagtail_color_panel.fields.ColorField(default='#ffffff', help_text='Light mode: Default background for body.<br>Default: <code>#ffffff</code>', max_length=7, verbose_name='Body background (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='body_color_dark',
            field=wagtail_color_panel.fields.ColorField(default='#dee2e6', help_text='Dark mode: Default foreground color for text.<br>Default: <code>#dee2e6</code>', max_length=7, verbose_name='Body text color (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='body_color_light',
            field=wagtail_color_panel.fields.ColorField(default='#212529', help_text='Light mode: Default foreground color for text.<br>Default: <code>#212529</code>', max_length=7, verbose_name='Body text color (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='border_color_dark',
            field=wagtail_color_panel.fields.ColorField(default='#495057', help_text='Dark mode: For component borders, dividers, and rules.<br>Default: <code>#495057</code>', max_length=7, verbose_name='Border color (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='border_color_light',
            field=wagtail_color_panel.fields.ColorField(default='#dee2e6', help_text='Light mode: For component borders, dividers, and rules.<br>Default: <code>#dee2e6</code>', max_length=7, verbose_name='Border color (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='danger_bg_subtle_dark',
            field=wagtail_color_panel.fields.ColorField(default='#2c0b0e', help_text='Dark mode: Subtle danger background.<br>Default: <code>#2c0b0e</code>', max_length=7, verbose_name='Danger subtle background (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='danger_bg_subtle_light',
            field=wagtail_color_panel.fields.ColorField(default='#f8d7da', help_text='Light mode: Subtle danger background.<br>Default: <code>#f8d7da</code>', max_length=7, verbose_name='Danger subtle background (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='danger_border_subtle_dark',
            field=wagtail_color_panel.fields.ColorField(default='#842029', help_text='Dark mode: Subtle danger border.<br>Default: <code>#842029</code>', max_length=7, verbose_name='Danger subtle border (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='danger_border_subtle_light',
            field=wagtail_color_panel.fields.ColorField(default='#f1aeb5', help_text='Light mode: Subtle danger border.<br>Default: <code>#f1aeb5</code>', max_length=7, verbose_name='Danger subtle border (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='danger_color',
            field=wagtail_color_panel.fields.ColorField(default='#dc3545', help_text='Theme color for errors and dangerous actions.<br>Default: <code>#dc3545</code>', max_length=7, verbose_name='Danger'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='danger_text_emphasis_dark',
            field=wagtail_color_panel.fields.ColorField(default='#ea868f', help_text='Dark mode: Emphasized danger text.<br>Default: <code>#ea868f</code>', max_length=7, verbose_name='Danger text emphasis (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='danger_text_emphasis_light',
            field=wagtail_color_panel.fields.ColorField(default='#58151c', help_text='Light mode: Emphasized danger text.<br>Default: <code>#58151c</code>', max_length=7, verbose_name='Danger text emphasis (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='dark_bg_subtle_dark',
            field=wagtail_color_panel.fields.ColorField(default='#1a1d20', help_text='Dark mode: Subtle dark background.<br>Default: <code>#1a1d20</code>', max_length=7, verbose_name='Dark subtle background (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='dark_bg_subtle_light',
            field=wagtail_color_panel.fields.ColorField(default='#ced4da', help_text='Light mode: Subtle dark background.<br>Default: <code>#ced4da</code>', max_length=7, verbose_name='Dark subtle background (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='dark_border_subtle_dark',
            field=wagtail_color_panel.fields.ColorField(default='#343a40', help_text='Dark mode: Subtle dark border.<br>Default: <code>#343a40</code>', max_length=7, verbose_name='Dark subtle border (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='dark_border_subtle_light',
            field=wagtail_color_panel.fields.ColorField(default='#adb5bd', help_text='Light mode: Subtle dark border.<br>Default: <code>#adb5bd</code>', max_length=7, verbose_name='Dark subtle border (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='dark_color',
            field=wagtail_color_panel.fields.ColorField(default='#212529', help_text='Additional theme option for higher contrasting colors.<br>Default: <code>#212529</code>', max_length=7, verbose_name='Dark'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='dark_text_emphasis_dark',
            field=wagtail_color_panel.fields.ColorField(default='#dee2e6', help_text='Dark mode: Emphasized dark text.<br>Default: <code>#dee2e6</code>', max_length=7, verbose_name='Dark text emphasis (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='dark_text_emphasis_light',
            field=wagtail_color_panel.fields.ColorField(default='#495057', help_text='Light mode: Emphasized dark text.<br>Default: <code>#495057</code>', max_length=7, verbose_name='Dark text emphasis (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='emphasis_color_dark',
            field=wagtail_color_panel.fields.ColorField(default='#ffffff', help_text='Dark mode: For higher contrast text.<br>Default: <code>#ffffff</code>', max_length=7, verbose_name='Emphasis color (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='emphasis_color_light',
            field=wagtail_color_panel.fields.ColorField(default='#000000', help_text='Light mode: For higher contrast text.<br>Default: <code>#000000</code>', max_length=7, verbose_name='Emphasis color (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='info_bg_subtle_dark',
            field=wagtail_color_panel.fields.ColorField(default='#032830', help_text='Dark mode: Subtle info background.<br>Default: <code>#032830</code>', max_length=7, verbose_name='Info subtle background (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='info_bg_subtle_light',
            field=wagtail_color_panel.fields.ColorField(default='#cff4fc', help_text='Light mode: Subtle info background.<br>Default: <code>#cff4fc</code>', max_length=7, verbose_name='Info subtle background (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='info_border_subtle_dark',
            field=wagtail_color_panel.fields.ColorField(default='#087990', help_text='Dark mode: Subtle info border.<br>Default: <code>#087990</code>', max_length=7, verbose_name='Info subtle border (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='info_border_subtle_light',
            field=wagtail_color_panel.fields.ColorField(default='#9eeaf9', help_text='Light mode: Subtle info border.<br>Default: <code>#9eeaf9</code>', max_length=7, verbose_name='Info subtle border (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='info_color',
            field=wagtail_color_panel.fields.ColorField(default='#0dcaf0', help_text='Theme color for neutral and informative content.<br>Default: <code>#0dcaf0</code>', max_length=7, verbose_name='Info'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='info_text_emphasis_dark',
            field=wagtail_color_panel.fields.ColorField(default='#6edff6', help_text='Dark mode: Emphasized info text.<br>Default: <code>#6edff6</code>', max_length=7, verbose_name='Info text emphasis (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='info_text_emphasis_light',
            field=wagtail_color_panel.fields.ColorField(default='#055160', help_text='Light mode: Emphasized info text.<br>Default: <code>#055160</code>', max_length=7, verbose_name='Info text emphasis (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='light_bg_subtle_dark',
            field=wagtail_color_panel.fields.ColorField(default='#343a40', help_text='Dark mode: Subtle light background.<br>Default: <code>#343a40</code>', max_length=7, verbose_name='Light subtle background (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='light_bg_subtle_light',
            field=wagtail_color_panel.fields.ColorField(default='#fcfcfd', help_text='Light mode: Subtle light background.<br>Default: <code>#fcfcfd</code>', max_length=7, verbose_name='Light subtle background (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='light_border_subtle_dark',
            field=wagtail_color_panel.fields.ColorField(default='#495057', help_text='Dark mode: Subtle light border.<br>Default: <code>#495057</code>', max_length=7, verbose_name='Light subtle border (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='light_border_subtle_light',
            field=wagtail_color_panel.fields.ColorField(default='#e9ecef', help_text='Light mode: Subtle light border.<br>Default: <code>#e9ecef</code>', max_length=7, verbose_name='Light subtle border (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='light_color',
            field=wagtail_color_panel.fields.ColorField(default='#f8f9fa', help_text='Additional theme option for less contrasting colors.<br>Default: <code>#f8f9fa</code>', max_length=7, verbose_name='Light'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='light_text_emphasis_dark',
            field=wagtail_color_panel.fields.ColorField(default='#f8f9fa', help_text='Dark mode: Emphasized light text.<br>Default: <code>#f8f9fa</code>', max_length=7, verbose_name='Light text emphasis (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='light_text_emphasis_light',
            field=wagtail_color_panel.fields.ColorField(default='#495057', help_text='Light mode: Emphasized light text.<br>Default: <code>#495057</code>', max_length=7, verbose_name='Light text emphasis (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='link_color_dark',
            field=wagtail_color_panel.fields.ColorField(default='#6ea8fe', help_text='Dark mode: Default hyperlink color.<br>Default: <code>#6ea8fe</code>', max_length=7, verbose_name='Link color (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='link_color_light',
            field=wagtail_color_panel.fields.ColorField(default='#0d6efd', help_text='Light mode: Default hyperlink color.<br>Default: <code>#0d6efd</code>', max_length=7, verbose_name='Link color (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='link_hover_color_dark',
            field=wagtail_color_panel.fields.ColorField(default='#8bb9fe', help_text='Dark mode: Hyperlink hover color.<br>Default: <code>#8bb9fe</code>', max_length=7, verbose_name='Link hover color (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='link_hover_color_light',
            field=wagtail_color_panel.fields.ColorField(default='#0a58ca', help_text='Light mode: Hyperlink hover color.<br>Default: <code>#0a58ca</code>', max_length=7, verbose_name='Link hover color (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='primary_bg_subtle_dark',
            field=wagtail_color_panel.fields.ColorField(default='#031633', help_text='Dark mode: Subtle primary background.<br>Default: <code>#031633</code>', max_length=7, verbose_name='Primary subtle background (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='primary_bg_subtle_light',
            field=wagtail_color_panel.fields.ColorField(default='#cfe2ff', help_text='Light mode: Subtle primary background.<br>Default: <code>#cfe2ff</code>', max_length=7, verbose_name='Primary subtle background (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='primary_border_subtle_dark',
            field=wagtail_color_panel.fields.ColorField(default='#084298', help_text='Dark mode: Subtle primary border.<br>Default: <code>#084298</code>', max_length=7, verbose_name='Primary subtle border (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='primary_border_subtle_light',
            field=wagtail_color_panel.fields.ColorField(default='#9ec5fe', help_text='Light mode: Subtle primary border.<br>Default: <code>#9ec5fe</code>', max_length=7, verbose_name='Primary subtle border (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='primary_color',
            field=wagtail_color_panel.fields.ColorField(default='#0d6efd', help_text='Main theme color for hyperlinks, focus styles, and active states.<br>Default: <code>#0d6efd</code>', max_length=7, verbose_name='Primary'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='primary_text_emphasis_dark',
            field=wagtail_color_panel.fields.ColorField(default='#6ea8fe', help_text='Dark mode: Emphasized primary text.<br>Default: <code>#6ea8fe</code>', max_length=7, verbose_name='Primary text emphasis (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='primary_text_emphasis_light',
            field=wagtail_color_panel.fields.ColorField(default='#052c65', help_text='Light mode: Emphasized primary text.<br>Default: <code>#052c65</code>', max_length=7, verbose_name='Primary text emphasis (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='secondary_bg_dark',
            field=wagtail_color_panel.fields.ColorField(default='#343a40', help_text='Dark mode: For dividers and disabled states.<br>Default: <code>#343a40</code>', max_length=7, verbose_name='Secondary background (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='secondary_bg_light',
            field=wagtail_color_panel.fields.ColorField(default='#e9ecef', help_text='Light mode: For dividers and disabled states.<br>Default: <code>#e9ecef</code>', max_length=7, verbose_name='Secondary background (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='secondary_color_dark',
            field=wagtail_color_panel.fields.ColorField(default='#dee2e6', help_text='Dark mode: Lighter text color option.<br>Default: <code>#dee2e6</code>', max_length=7, verbose_name='Secondary text (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='secondary_color_light',
            field=wagtail_color_panel.fields.ColorField(default='#6c757d', help_text='Light mode: Lighter text color option.<br>Default: <code>#6c757d</code>', max_length=7, verbose_name='Secondary text (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='success_bg_subtle_dark',
            field=wagtail_color_panel.fields.ColorField(default='#051b11', help_text='Dark mode: Subtle success background.<br>Default: <code>#051b11</code>', max_length=7, verbose_name='Success subtle background (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='success_bg_subtle_light',
            field=wagtail_color_panel.fields.ColorField(default='#d1e7dd', help_text='Light mode: Subtle success background.<br>Default: <code>#d1e7dd</code>', max_length=7, verbose_name='Success subtle background (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='success_border_subtle_dark',
            field=wagtail_color_panel.fields.ColorField(default='#0f5132', help_text='Dark mode: Subtle success border.<br>Default: <code>#0f5132</code>', max_length=7, verbose_name='Success subtle border (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='success_border_subtle_light',
            field=wagtail_color_panel.fields.ColorField(default='#a3cfbb', help_text='Light mode: Subtle success border.<br>Default: <code>#a3cfbb</code>', max_length=7, verbose_name='Success subtle border (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='success_color',
            field=wagtail_color_panel.fields.ColorField(default='#198754', help_text='Theme color for positive or successful actions.<br>Default: <code>#198754</code>', max_length=7, verbose_name='Success'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='success_text_emphasis_dark',
            field=wagtail_color_panel.fields.ColorField(default='#75b798', help_text='Dark mode: Emphasized success text.<br>Default: <code>#75b798</code>', max_length=7, verbose_name='Success text emphasis (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='success_text_emphasis_light',
            field=wagtail_color_panel.fields.ColorField(default='#0a3622', help_text='Light mode: Emphasized success text.<br>Default: <code>#0a3622</code>', max_length=7, verbose_name='Success text emphasis (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='tertiary_bg_dark',
            field=wagtail_color_panel.fields.ColorField(default='#2b3035', help_text='Dark mode: For hover states, accents, and wells.<br>Default: <code>#2b3035</code>', max_length=7, verbose_name='Tertiary background (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='tertiary_bg_light',
            field=wagtail_color_panel.fields.ColorField(default='#f8f9fa', help_text='Light mode: For hover states, accents, and wells.<br>Default: <code>#f8f9fa</code>', max_length=7, verbose_name='Tertiary background (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='tertiary_color_dark',
            field=wagtail_color_panel.fields.ColorField(default='#dee2e6', help_text='Dark mode: Even lighter text color option.<br>Default: <code>#dee2e6</code>', max_length=7, verbose_name='Tertiary text (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='tertiary_color_light',
            field=wagtail_color_panel.fields.ColorField(default='#6c757d', help_text='Light mode: Even lighter text color option.<br>Default: <code>#6c757d</code>', max_length=7, verbose_name='Tertiary text (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='warning_bg_subtle_dark',
            field=wagtail_color_panel.fields.ColorField(default='#332701', help_text='Dark mode: Subtle warning background.<br>Default: <code>#332701</code>', max_length=7, verbose_name='Warning subtle background (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='warning_bg_subtle_light',
            field=wagtail_color_panel.fields.ColorField(default='#fff3cd', help_text='Light mode: Subtle warning background.<br>Default: <code>#fff3cd</code>', max_length=7, verbose_name='Warning subtle background (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='warning_border_subtle_dark',
            field=wagtail_color_panel.fields.ColorField(default='#997404', help_text='Dark mode: Subtle warning border.<br>Default: <code>#997404</code>', max_length=7, verbose_name='Warning subtle border (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='warning_border_subtle_light',
            field=wagtail_color_panel.fields.ColorField(default='#ffe69c', help_text='Light mode: Subtle warning border.<br>Default: <code>#ffe69c</code>', max_length=7, verbose_name='Warning subtle border (light)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='warning_color',
            field=wagtail_color_panel.fields.ColorField(default='#ffc107', help_text='Theme color for non-destructive warning messages.<br>Default: <code>#ffc107</code>', max_length=7, verbose_name='Warning'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='warning_text_emphasis_dark',
            field=wagtail_color_panel.fields.ColorField(default='#ffda6a', help_text='Dark mode: Emphasized warning text.<br>Default: <code>#ffda6a</code>', max_length=7, verbose_name='Warning text emphasis (dark)'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='warning_text_emphasis_light',
            field=wagtail_color_panel.fields.ColorField(default='#664d03', help_text='Light mode: Emphasized warning text.<br>Default: <code>#664d03</code>', max_length=7, verbose_name='Warning text emphasis (light)'),
        ),
    ]
