# Generated by Django 5.2.8 on 2025-12-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_alter_themesettings_body_bg_dark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='body_font_family',
            field=models.CharField(default='var(--bs-font-sans-serif)', help_text='Font family for body text. Typically references --bs-font-sans-serif.<br>Default: <code>var(--bs-font-sans-serif)</code>', max_length=100, verbose_name='Body font family'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='body_font_size',
            field=models.CharField(default='1rem', help_text='Base font size for body text.<br>Default: <code>1rem</code>', max_length=50, verbose_name='Body font size'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='body_font_weight',
            field=models.CharField(default='400', help_text='Font weight for body text.<br>Default: <code>400</code>', max_length=50, verbose_name='Body font weight'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='body_line_height',
            field=models.CharField(default='1.5', help_text='Line height for body text.<br>Default: <code>1.5</code>', max_length=50, verbose_name='Body line height'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='font_monospace',
            field=models.CharField(default='SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace', help_text='Default monospace font stack for code and pre elements.<br>Default: SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace', max_length=500, verbose_name='Monospace font stack'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='font_sans_serif',
            field=models.CharField(default='system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", "Liberation Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"', help_text='Sans-serif font stack for the site.<br>Default: system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", "Liberation Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"', max_length=500, verbose_name='Sans-serif font stack'),
        ),
    ]
