# Generated by Django 5.2.8 on 2025-12-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_themesettings_body_font_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='custom_css',
            field=models.TextField(blank=True, default='', help_text='<strong>⚠️ WARNING:</strong> Direct CSS overrides can break site layout and styling. Use with caution. Invalid CSS may cause display issues. This field accepts pure CSS code that will be injected into all pages.', verbose_name='Custom CSS'),
        ),
    ]
