# Generated by Django 5.2.8 on 2025-12-19 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_add_custom_css_to_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themesettings',
            name='css_version',
        ),
        migrations.CreateModel(
            name='ThemeSettingsRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(help_text='Snapshot of all theme settings at the time of save')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this revision was created')),
                ('settings', models.ForeignKey(help_text='The theme settings this revision belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='cms.themesettings')),
            ],
            options={
                'verbose_name': 'Theme Settings Revision',
                'verbose_name_plural': 'Theme Settings Revisions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['settings', '-created_at'], name='cms_themese_setting_81854d_idx')],
            },
        ),
    ]
