# Generated by Django 5.2.8 on 2025-12-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_add_theme_settings_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='cache_version',
            field=models.IntegerField(default=1, editable=False, help_text='Auto-incremented on save to invalidate cached CSS'),
        ),
    ]
