# Generated by Django 5.2.8 on 2025-12-20 20:48

import wagtail_color_panel.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0028_alter_contentpage_body_alter_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='footer_bg_color',
            field=wagtail_color_panel.fields.ColorField(default='#f8f9fa', help_text='Background color for the footer.<br>Default: <code>#f8f9fa</code> (light gray)', max_length=7, verbose_name='Footer background color'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_colour_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', help_text='Color mode for the footer (determines text color contrast)', max_length=10, verbose_name='Footer color mode'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='navbar_bg_color',
            field=wagtail_color_panel.fields.ColorField(default='#f8f9fa', help_text='Background color for the navigation bar.<br>Default: <code>#f8f9fa</code> (light gray)', max_length=7, verbose_name='Navbar background color'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='navbar_colour_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', help_text='Color mode for the navbar (determines text color contrast)', max_length=10, verbose_name='Navbar color mode'),
        ),
    ]
