# Generated by Django 5.2.8 on 2026-01-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_alter_articlepage_body_alter_contentpage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English')], max_length=10, verbose_name='Language'),
        ),
    ]
