# Generated by Django 5.2.8 on 2026-01-13 07:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0038_alter_articlepage_body_alter_contentpage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationsettings',
            name='footer_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional footer text (e.g., copyright info, disclaimers).'),
        ),
    ]
