# Generated by Django 5.2.8 on 2026-01-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0039_associationsettings_footer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='is_structure_only',
            field=models.BooleanField(default=False, help_text='If checked, this page cannot be viewed directly and will redirect to its first child page.'),
        ),
    ]
