# Generated by Django 5.2.8 on 2026-01-17 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0040_contentpage_is_structure_only'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='Shown on cards that link to the full article', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
