# Generated by Django 5.2.15 on 2026-06-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0042_alter_articlepage_body_alter_contentpage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('mi', 'Te Reo Māori')], max_length=10, verbose_name='Language'),
        ),
    ]
