# Generated by Django 5.2.15 on 2026-06-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0044_alter_articlepage_body_alter_contentpage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='custom_html',
            field=models.TextField(blank=True, default='', help_text="<strong>⚠️ WARNING:</strong> Raw HTML injected into every page's <code>&lt;head&gt;</code>. Useful for Google Fonts <code>&lt;link&gt;</code> tags, analytics scripts, or meta tags. Invalid or malicious HTML may break pages or introduce security risks. This field accepts raw HTML that will be injected into all pages.", verbose_name='Custom HTML (head)'),
        ),
    ]
