# Generated by Django 5.2.15 on 2026-06-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0045_add_custom_html_to_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='base_colour_mode',
            field=models.CharField(choices=[('light', 'Light background, dark text'), ('dark', 'Dark background, light text')], default='light', help_text='Color mode for the page (determines Bootstrap component styles for text, forms, buttons, etc.)', max_length=10, verbose_name='Base color mode'),
        ),
    ]
