# Generated by Django 5.2.15 on 2026-06-29 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0046_themesettings_base_colour_mode'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='separator_image',
            field=models.ForeignKey(blank=True, help_text="Image to tile horizontally. Used when separator type is 'Tiled image'. PNG or SVG recommended.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Separator image'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='separator_type',
            field=models.CharField(choices=[('line', 'Line'), ('image', 'Tiled image')], default='line', help_text='Default horizontal separator style. Authors can override per block.', max_length=10, verbose_name='Separator type'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='separator_width',
            field=models.CharField(choices=[('content', 'Content width'), ('full', 'Full window width')], default='content', help_text='Default width for horizontal separators.', max_length=10, verbose_name='Separator width'),
        ),
    ]
