# Generated by Django 5.2.15 on 2026-06-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0047_themesettings_separator_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesettings',
            name='separator_type',
            field=models.CharField(choices=[('line', 'Line'), ('image', 'Tiled image'), ('centered', 'Centered image')], default='line', help_text='Default horizontal separator style. Authors can override per block.', max_length=10, verbose_name='Separator type'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='separator_width',
            field=models.CharField(choices=[('content', 'Content width'), ('full', 'Full window width')], default='content', help_text="Default width for horizontal separators. Note: 'Full window width' may not render correctly inside column blocks.", max_length=10, verbose_name='Separator width'),
        ),
    ]
