# Generated by Django 5.2.15 on 2026-06-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0052_themesettings_primary_btn_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='btn_font_weight',
            field=models.CharField(default='400', help_text='Font weight for all buttons.<br>Common values: <code>400</code> (normal), <code>600</code> (semi-bold), <code>700</code> (bold).<br>Default: <code>400</code>', max_length=10, verbose_name='Button font weight'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='navbar_signin_style',
            field=models.CharField(choices=[('link', 'Link (default)'), ('outline', 'Outlined button'), ('solid', 'Filled button')], default='link', help_text='How the Sign In link in the navbar is rendered.', max_length=10, verbose_name='Sign In style'),
        ),
    ]
