# Generated by Django 5.2.15 on 2026-06-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0053_themesettings_signin_style_btn_font_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='navbar_signup_style',
            field=models.CharField(choices=[('link', 'Link'), ('outline', 'Outlined button'), ('solid', 'Filled button (default)')], default='solid', help_text='How the Sign Up link in the navbar is rendered.', max_length=10, verbose_name='Sign Up style'),
        ),
    ]
