# Generated by Django 5.2.15 on 2026-06-30 22:38

import wagtail_color_panel.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0054_themesettings_navbar_signup_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='navbar_toggler_color',
            field=wagtail_color_panel.fields.ColorField(default='#dee2e6', help_text='Color for the hamburger menu button.<br>Choose a color that contrasts with your navbar background.<br>Default: <code>#dee2e6</code>', max_length=7, verbose_name='Navbar toggler color'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='primary_btn_text_color',
            field=wagtail_color_panel.fields.ColorField(default='#ffffff', help_text='Text color for filled primary buttons (e.g. <code>btn-primary</code>).<br>Ensure sufficient contrast with your primary color(WCAG AA requires 4.5:1).<br>Default: <code>#ffffff</code> (white)', max_length=7, verbose_name='Primary button text color'),
        ),
    ]
