# Generated by Django 5.2.15 on 2026-07-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0055_themesettings_navbar_toggler_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationsettings',
            name='navbar_signin_label',
            field=models.CharField(blank=True, help_text="Custom text for the Sign In button in the navbar. Leave blank to use the default 'Sign In' text.", max_length=50, verbose_name='Sign In label'),
        ),
        migrations.AddField(
            model_name='associationsettings',
            name='navbar_signup_label',
            field=models.CharField(blank=True, help_text="Custom text for the Sign Up button in the navbar. Leave blank to use the default 'Sign Up' text.", max_length=50, verbose_name='Sign Up label'),
        ),
    ]
