# Generated by Django 5.2.15 on 2026-07-04 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0057_alter_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='css_id',
            field=models.CharField(blank=True, default='', help_text="Optional identifier rendered as the id attribute on this page's <body> tag. Use it to target this page with custom CSS rules (e.g. #my-page-id .some-class) in the theme's Custom CSS field. Must start with a letter; only letters, numbers, hyphens, and underscores allowed.", max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_css_id', message='CSS ID must start with a letter and contain only letters, numbers, hyphens, and underscores.', regex='^[a-zA-Z][a-zA-Z0-9_-]*$')], verbose_name='CSS ID'),
        ),
        migrations.AddField(
            model_name='articlesindexpage',
            name='css_id',
            field=models.CharField(blank=True, default='', help_text="Optional identifier rendered as the id attribute on this page's <body> tag. Use it to target this page with custom CSS rules (e.g. #my-page-id .some-class) in the theme's Custom CSS field. Must start with a letter; only letters, numbers, hyphens, and underscores allowed.", max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_css_id', message='CSS ID must start with a letter and contain only letters, numbers, hyphens, and underscores.', regex='^[a-zA-Z][a-zA-Z0-9_-]*$')], verbose_name='CSS ID'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='css_id',
            field=models.CharField(blank=True, default='', help_text="Optional identifier rendered as the id attribute on this page's <body> tag. Use it to target this page with custom CSS rules (e.g. #my-page-id .some-class) in the theme's Custom CSS field. Must start with a letter; only letters, numbers, hyphens, and underscores allowed.", max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_css_id', message='CSS ID must start with a letter and contain only letters, numbers, hyphens, and underscores.', regex='^[a-zA-Z][a-zA-Z0-9_-]*$')], verbose_name='CSS ID'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='css_id',
            field=models.CharField(blank=True, default='', help_text="Optional identifier rendered as the id attribute on this page's <body> tag. Use it to target this page with custom CSS rules (e.g. #my-page-id .some-class) in the theme's Custom CSS field. Must start with a letter; only letters, numbers, hyphens, and underscores allowed.", max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_css_id', message='CSS ID must start with a letter and contain only letters, numbers, hyphens, and underscores.', regex='^[a-zA-Z][a-zA-Z0-9_-]*$')], verbose_name='CSS ID'),
        ),
    ]
