# Generated by Django 5.2.17 on 2026-10-09 07:58

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0058_add_css_id_to_basepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amsdocument',
            name='file',
            field=models.FileField(storage=config.storage_backends.PrivateMediaStorage(access_key='admin', bucket_name='ams-media-private', custom_domain='localhost:9000/ams-media-private', endpoint_url='http://file-store:9000', region_name=None, secret_key='password'), upload_to='documents', verbose_name='file'),
        ),
    ]
