# Generated by Django 4.2.7 on 2024-02-06 19:51

from typing import Any

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0011_add_organisation_membership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    def create_accounts_for_existing_users_and_organisations(apps: Any, schema_editor: Any) -> None:
        Account = apps.get_model("billing.Account")

        User = apps.get_model(settings.AUTH_USER_MODEL)
        Organisation = apps.get_model("users.Organisation")

        for user in User.objects.all().order_by("id"):
            Account.objects.create(user=user)

        for organisation in Organisation.objects.all().order_by("id"):
            Account.objects.create(organisation=organisation)

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "organisation",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to="users.organisation",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(
                check=models.Q(("organisation__isnull", False), ("user__isnull", False), _connector="OR"),
                name="check_has_user_or_organisation",
            ),
        ),
        migrations.RunPython(create_accounts_for_existing_users_and_organisations),
    ]
