# Generated by Django 4.2.7 on 2024-02-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="billing_service_invoice_id",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
