# Generated by Django 4.2.7 on 2024-02-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_invoice_billing_service_invoice_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="paid_date",
            field=models.DateField(null=True),
        ),
    ]
