# Generated by Django 5.2.5 on 2025-10-12 08:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_name_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('postal_address', models.CharField(max_length=255)),
                ('postal_suburb', models.CharField(blank=True, max_length=255)),
                ('postal_city', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('suburb', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisations', to='users.organisationtype')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_email', models.CharField(blank=True, max_length=255)),
                ('invite_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_datetime', models.DateTimeField()),
                ('accepted_datetime', models.DateTimeField(null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_members', to='users.organisation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'organisation')},
            },
        ),
    ]
