# Generated by Django 5.2.5 on 2025-10-25 09:09 and manually changes to migrate existing users

import django.contrib.auth.validators
from django.db import migrations, models

def set_username_to_id(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        user.username = str(user.id)
        user.save(update_fields=['username'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_organisationtype_organisation_organisationmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(
                error_messages={'unique': 'A user with that username already exists.'},
                help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
                max_length=150,
                unique=False,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name='username',
                blank=True,
                null=True,
            ),
        ),
        migrations.RunPython(set_username_to_id, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                error_messages={'unique': 'A user with that username already exists.'},
                help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name='username',
                blank=False,
                null=False,
            ),
        ),
    ]
