# Generated by Django 5.2.5 on 2025-10-26 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='This is used in the community forum.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must only include numbers, letters (including macrons), dashes, dots, and underscores.', regex='^[a-zA-ZāēīōūĀĒĪŌŪ0-9._-]+$')], verbose_name='username'),
        ),
    ]
