# Generated by Django 5.2.8 on 2025-12-08 08:33

import ams.users.models
import config.storage_backends
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, storage=config.storage_backends.PublicMediaStorage, upload_to=ams.users.models.user_profile_picture_path, verbose_name='profile picture'),
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
