# Generated by Django 5.2.8 on 2025-12-08 08:33

import uuid

from django.db import migrations


def populate_user_uuids(apps, schema_editor):
    """Generate unique UUIDs for existing users."""
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        user.uuid = uuid.uuid4()
        user.save(update_fields=["uuid"])


def reverse_populate_user_uuids(apps, schema_editor):
    """Reverse operation - set UUIDs to None."""
    User = apps.get_model("users", "User")
    User.objects.all().update(uuid=None)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_profile_picture_user_uuid'),
    ]

    operations = [
        migrations.RunPython(populate_user_uuids, reverse_populate_user_uuids),
    ]
