# Generated by Django 5.2.8 on 2025-12-10 08:20

import ams.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, storage=ams.users.models.get_public_media_storage, upload_to=ams.users.models.user_profile_picture_path, verbose_name='profile picture'),
        ),
    ]
