# Generated by Django 5.2.8 on 2025-12-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_organisation_uuid_organisationmember_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='type',
        ),
        migrations.RemoveField(
            model_name='organisationmember',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='organisationmember',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', help_text='Member role within the organisation', max_length=10),
        ),
        migrations.DeleteModel(
            name='OrganisationType',
        ),
    ]
