# Generated by Django 5.2.8 on 2025-12-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_organisation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationmember',
            name='declined_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
