# Generated by Django 5.2.8 on 2025-12-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_add_declined_datetime_to_organisation_member'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organisationmember',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='organisationmember',
            constraint=models.UniqueConstraint(condition=models.Q(('declined_datetime__isnull', True)), fields=('user', 'organisation'), name='unique_active_org_member'),
        ),
    ]
