# Generated by Django 5.2.8 on 2026-01-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_organisation_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for administrators only.', verbose_name='admin notes'),
        ),
    ]
