# Generated by Django 5.2.8 on 2026-01-18 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_admin_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileFieldGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_translations', models.JSONField(default=dict, help_text='Enter translations as JSON: {"en": "Name", "mi": "Ingoa"}', verbose_name='name translations')),
                ('description_translations', models.JSONField(blank=True, default=dict, help_text='Enter translations as JSON: {"en": "Description", "mi": "Whakamārama"}', verbose_name='description translations')),
                ('order', models.IntegerField(default=0, help_text='Display order', verbose_name='order')),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide group', verbose_name='is active')),
            ],
            options={
                'verbose_name': 'profile field group',
                'verbose_name_plural': 'profile field groups',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProfileField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(help_text='Unique identifier (lowercase_underscore format)', max_length=100, unique=True, verbose_name='field key')),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('TEXTAREA', 'Textarea'), ('CHECKBOX', 'Checkbox'), ('RADIO', 'Radio'), ('DATE', 'Date'), ('MONTH', 'Month'), ('NUMBER', 'Number'), ('SELECT', 'Select')], help_text='Type of form field', max_length=20, verbose_name='field type')),
                ('label_translations', models.JSONField(default=dict, help_text='Enter translations as JSON: {"en": "Label", "mi": "Tapanga"}', verbose_name='label translations')),
                ('help_text_translations', models.JSONField(blank=True, default=dict, help_text='Enter translations as JSON: {"en": "Help text", "mi": "Āwhina"}', verbose_name='help text translations')),
                ('options', models.JSONField(blank=True, default=dict, help_text='For select/radio/checkbox: {"choices": [{"value": "val1", "label_translations": {"en": "Label 1", "mi": "..."}}]}', verbose_name='options')),
                ('min_value', models.IntegerField(blank=True, help_text='Minimum value for number fields', null=True, verbose_name='min value')),
                ('max_value', models.IntegerField(blank=True, help_text='Maximum value for number fields', null=True, verbose_name='max value')),
                ('is_read_only', models.BooleanField(default=False, help_text='Only admins can set value', verbose_name='is read only')),
                ('is_required_for_membership', models.BooleanField(default=False, help_text='Required before membership purchase', verbose_name='is required for membership')),
                ('order', models.IntegerField(default=0, help_text='Display order within group', verbose_name='order')),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide field', verbose_name='is active')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='users.profilefieldgroup', verbose_name='group')),
            ],
            options={
                'verbose_name': 'profile field',
                'verbose_name_plural': 'profile fields',
                'ordering': ['order'],
                'unique_together': {('group', 'field_key')},
            },
        ),
        migrations.CreateModel(
            name='ProfileFieldResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, help_text='Response value', verbose_name='value')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='When response was last updated', verbose_name='updated datetime')),
                ('profile_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='users.profilefield', verbose_name='profile field')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_responses', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'profile field response',
                'verbose_name_plural': 'profile field responses',
                'indexes': [models.Index(fields=['user'], name='users_profi_user_id_74c3a2_idx'), models.Index(fields=['profile_field'], name='users_profi_profile_7187e8_idx')],
                'unique_together': {('user', 'profile_field')},
            },
        ),
    ]
