# Generated by Django 5.2.8 on 2026-01-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_add_profile_field_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefield',
            name='counts_toward_completion',
            field=models.BooleanField(default=True, help_text='Include this field in profile completion percentage', verbose_name='recommended to complete'),
        ),
    ]
