# Generated by Django 5.2.15 on 2026-06-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_profilefield_counts_toward_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('mi', 'Te Reo Māori')], default='', max_length=10, verbose_name='preferred language'),
        ),
    ]
