# Generated by Django 5.2.8 on 2025-12-15 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_invoice_paid_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XeroMutex',
        ),
    ]
