# Generated by Django 5.2.8 on 2026-01-01 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_delete_xeromutex'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='organisation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='organisations.organisation'),
        ),
    ]
