# Generated by Django 5.2.8 on 2026-01-05 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_account_organisation'),
        ('memberships', '0012_membershipoption_voting_rights'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='individual_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='memberships.individualmembership'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='organisation_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='memberships.organisationmembership'),
        ),
    ]
