# Generated by Django 5.2.8 on 2026-02-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_invoice_individual_membership_and_more'),
        ('memberships', '0019_individualmembership_idx_indiv_mem_active_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['individual_membership', 'paid_date'], name='idx_invoice_indiv'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organisation_membership', 'paid_date'], name='idx_invoice_org'),
        ),
    ]
