# Generated by Django 5.2.11 on 2026-02-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_invoice_idx_invoice_indiv_invoice_idx_invoice_org'),
        ('memberships', '0019_individualmembership_idx_indiv_mem_active_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['billing_service_invoice_id'], name='idx_invoice_xero_id'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['update_needed'], name='idx_invoice_update_flag'),
        ),
    ]
