# Generated by Django 5.2.16 on 2026-07-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_invoice_idx_invoice_xero_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='update_requested_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
