# Generated by Django 5.2.12 on 2026-04-11 01:16

import ams.resources.utils
import autoslug.fields
import config.storage_backends
import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from='name')),
                ('description', tinymce.models.HTMLField()),
                ('published', models.BooleanField(default=False)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('author_entities', models.ManyToManyField(blank=True, related_name='resources', to='entities.entity')),
                ('author_users', models.ManyToManyField(blank=True, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime_updated'],
            },
        ),
        migrations.CreateModel(
            name='ResourceComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('component_type', models.PositiveSmallIntegerField(choices=[(0, 'Other'), (10, 'Document'), (11, 'PDF'), (90, 'Spreadsheet'), (20, 'Image'), (30, 'Slideshow'), (40, 'Video'), (50, 'Website'), (60, 'Audio'), (70, 'Archive'), (80, 'Resource')], default=0)),
                ('component_url', models.URLField(blank=True)),
                ('component_file', models.FileField(blank=True, null=True, storage=config.storage_backends.PrivateMediaStorage(), upload_to=ams.resources.utils.resource_upload_path)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('component_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component_of', to='resources.resource')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='resources.resource')),
            ],
        ),
    ]
