# Generated by Django 5.2.12 on 2026-04-12 08:51

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='resources_r_search__82e125_gin'),
        ),
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION resources_resource_search_vector_update()
                RETURNS trigger AS $$
                BEGIN
                    NEW.search_vector :=
                        setweight(to_tsvector('english', COALESCE(NEW.name, '')), 'A') ||
                        setweight(to_tsvector('english', COALESCE(NEW.description, '')), 'B');
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER resources_resource_search_vector_trigger
                BEFORE INSERT OR UPDATE OF name, description
                ON resources_resource
                FOR EACH ROW
                EXECUTE FUNCTION resources_resource_search_vector_update();

                UPDATE resources_resource SET search_vector =
                    setweight(to_tsvector('english', COALESCE(name, '')), 'A') ||
                    setweight(to_tsvector('english', COALESCE(description, '')), 'B');
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS resources_resource_search_vector_trigger ON resources_resource;
                DROP FUNCTION IF EXISTS resources_resource_search_vector_update();
            """,
        ),
    ]
