# Generated by Django 5.2.12 on 2026-04-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_resource_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='visibility',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Public - visible and downloadable by everyone'), (1, 'Account required to download - anyone can view, logged-in users can download'), (2, 'Membership required to download - anyone can view, only members can download files'), (3, 'Members only - only members can view or download')], default=0, help_text='Controls who can view and download this resource. Public: no restrictions. Account required to download: anyone can browse, logged-in users can download. Membership required to download: anyone can browse, members can download files. Members only: only members can view or download.'),
        ),
    ]
