# Generated by Django 5.2.12 on 2026-04-25 21:13

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_alter_resource_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcetag',
            name='css_class',
        ),
        migrations.AddField(
            model_name='resourcetag',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=25, samples=None),
        ),
    ]
