# Generated by Django 5.2.12 on 2026-04-26 00:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_remove_resourcetag_css_class_resourcetag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecomponent',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
