# Generated by Django 5.2.13 on 2026-05-04 06:32

import ams.resources.utils
import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_resourcecomponent_uuid_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcecomponent',
            name='component_file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=config.storage_backends.PrivateMediaStorage(), upload_to=ams.resources.utils.resource_upload_path),
        ),
    ]
