# Generated by Django 5.2.13 on 2026-05-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_alter_resourcecomponent_component_file_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='visibility',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Public - visible and accessable by everyone'), (1, 'Account required to access - anyone can view, logged-in users can access'), (2, 'Membership required to access - anyone can view, only members can access files'), (3, 'Members only - only members can view or access')], default=0, help_text='Controls who can view and access this resource. Public: no restrictions. Account required to access: anyone can browse, logged-in users can access. Membership required to access: anyone can browse, members can access files. Members only: only members can view or access.'),
        ),
    ]
