# Generated by Django 5.2.15 on 2026-06-22 01:25

import autoslug.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_alter_resource_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='description_mi',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='name_mi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='name_mi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resourcecomponent',
            name='name_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='resourcecomponent',
            name='name_mi',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='resourcetag',
            name='abbreviation_en',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resourcetag',
            name='abbreviation_mi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resourcetag',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resourcetag',
            name='name_mi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from='_slug_source'),
        ),
        migrations.AlterField(
            model_name='resourcecategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='_slug_source'),
        ),
        migrations.AlterField(
            model_name='resourcetag',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='_slug_source'),
        ),
    ]
