# Generated by Django 5.2.15 on 2026-07-15 22:57

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        ('resources', '0015_search_vector_translated_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='search_vector_en',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='search_vector_mi',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_en'], name='resources_r_search__438342_gin'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_mi'], name='resources_r_search__baaa4a_gin'),
        ),
        migrations.RunSQL(
            sql="""
                -- Split the single combined vector into one vector per language so
                -- search can be scoped to the active UI language. The English vector
                -- reads the _en columns with the 'english' config; the Maori vector
                -- reads the _mi columns with the 'simple' config, falling back per
                -- field to the _en value when the _mi value is blank (mirroring
                -- modeltranslation's display fallback). Author user and entity names
                -- are language-neutral and indexed in both vectors.
                DROP FUNCTION IF EXISTS resources_resource_compute_search_vector(bigint, text, text, text, text);

                CREATE OR REPLACE FUNCTION resources_resource_compute_search_vector_en(
                    p_id bigint,
                    p_name_en text,
                    p_description_en text,
                    p_name_mi text DEFAULT '',
                    p_description_mi text DEFAULT ''
                ) RETURNS tsvector AS $$
                    SELECT
                        setweight(to_tsvector('english', COALESCE(p_name_en, '')), 'A')
                        || setweight(to_tsvector('english', COALESCE(p_description_en, '')), 'B')
                        || setweight(to_tsvector('english', COALESCE(
                            (SELECT string_agg(c.name_en, ' ')
                             FROM resources_resourcecomponent c
                             WHERE c.resource_id = p_id), '')), 'B')
                        || setweight(to_tsvector('english', COALESCE(
                            (SELECT string_agg(u.first_name || ' ' || u.last_name, ' ')
                             FROM users_user u
                             INNER JOIN resources_resource_author_users m
                                 ON m.user_id = u.id
                             WHERE m.resource_id = p_id), '')), 'C')
                        || setweight(to_tsvector('english', COALESCE(
                            (SELECT string_agg(e.name, ' ')
                             FROM entities_entity e
                             INNER JOIN resources_resource_author_entities m
                                 ON m.entity_id = e.id
                             WHERE m.resource_id = p_id), '')), 'C')
                        || setweight(to_tsvector('english', COALESCE(
                            (SELECT string_agg(t.name_en, ' ')
                             FROM resources_resourcetag t
                             INNER JOIN resources_resource_tags m
                                 ON m.resourcetag_id = t.id
                             WHERE m.resource_id = p_id), '')), 'C')
                        || setweight(to_tsvector('english', COALESCE(
                            (SELECT string_agg(t.abbreviation_en, ' ')
                             FROM resources_resourcetag t
                             INNER JOIN resources_resource_tags m
                                 ON m.resourcetag_id = t.id
                             WHERE m.resource_id = p_id), '')), 'C');
                $$ LANGUAGE sql;

                CREATE OR REPLACE FUNCTION resources_resource_compute_search_vector_mi(
                    p_id bigint,
                    p_name_en text,
                    p_description_en text,
                    p_name_mi text DEFAULT '',
                    p_description_mi text DEFAULT ''
                ) RETURNS tsvector AS $$
                    SELECT
                        setweight(to_tsvector('simple', COALESCE(NULLIF(p_name_mi, ''), p_name_en, '')), 'A')
                        || setweight(to_tsvector('simple', COALESCE(NULLIF(p_description_mi, ''), p_description_en, '')), 'B')
                        || setweight(to_tsvector('simple', COALESCE(
                            (SELECT string_agg(COALESCE(NULLIF(c.name_mi, ''), c.name_en), ' ')
                             FROM resources_resourcecomponent c
                             WHERE c.resource_id = p_id), '')), 'B')
                        || setweight(to_tsvector('simple', COALESCE(
                            (SELECT string_agg(u.first_name || ' ' || u.last_name, ' ')
                             FROM users_user u
                             INNER JOIN resources_resource_author_users m
                                 ON m.user_id = u.id
                             WHERE m.resource_id = p_id), '')), 'C')
                        || setweight(to_tsvector('simple', COALESCE(
                            (SELECT string_agg(e.name, ' ')
                             FROM entities_entity e
                             INNER JOIN resources_resource_author_entities m
                                 ON m.entity_id = e.id
                             WHERE m.resource_id = p_id), '')), 'C')
                        || setweight(to_tsvector('simple', COALESCE(
                            (SELECT string_agg(COALESCE(NULLIF(t.name_mi, ''), t.name_en), ' ')
                             FROM resources_resourcetag t
                             INNER JOIN resources_resource_tags m
                                 ON m.resourcetag_id = t.id
                             WHERE m.resource_id = p_id), '')), 'C')
                        || setweight(to_tsvector('simple', COALESCE(
                            (SELECT string_agg(COALESCE(NULLIF(t.abbreviation_mi, ''), t.abbreviation_en), ' ')
                             FROM resources_resourcetag t
                             INNER JOIN resources_resource_tags m
                                 ON m.resourcetag_id = t.id
                             WHERE m.resource_id = p_id), '')), 'C');
                $$ LANGUAGE sql;

                -- Row-level trigger populates both vectors. Trigger definitions and
                -- their UPDATE OF column lists are unchanged from 0015, so only the
                -- function bodies are replaced here.
                CREATE OR REPLACE FUNCTION resources_resource_search_vector_update()
                RETURNS trigger AS $$
                BEGIN
                    NEW.search_vector_en := resources_resource_compute_search_vector_en(
                        NEW.id, NEW.name_en, NEW.description_en,
                        NEW.name_mi, NEW.description_mi
                    );
                    NEW.search_vector_mi := resources_resource_compute_search_vector_mi(
                        NEW.id, NEW.name_en, NEW.description_en,
                        NEW.name_mi, NEW.description_mi
                    );
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE OR REPLACE FUNCTION resources_resource_search_vector_refresh()
                RETURNS trigger AS $$
                BEGIN
                    UPDATE resources_resource SET
                        search_vector_en = resources_resource_compute_search_vector_en(
                            id, name_en, description_en, name_mi, description_mi),
                        search_vector_mi = resources_resource_compute_search_vector_mi(
                            id, name_en, description_en, name_mi, description_mi)
                    WHERE id = COALESCE(NEW.resource_id, OLD.resource_id);
                    RETURN NULL;
                END;
                $$ LANGUAGE plpgsql;

                CREATE OR REPLACE FUNCTION resources_resource_m2m_search_vector_refresh()
                RETURNS trigger AS $$
                BEGIN
                    UPDATE resources_resource SET
                        search_vector_en = resources_resource_compute_search_vector_en(
                            id, name_en, description_en, name_mi, description_mi),
                        search_vector_mi = resources_resource_compute_search_vector_mi(
                            id, name_en, description_en, name_mi, description_mi)
                    WHERE id = COALESCE(NEW.resource_id, OLD.resource_id);
                    RETURN NULL;
                END;
                $$ LANGUAGE plpgsql;

                CREATE OR REPLACE FUNCTION resources_resourcetag_search_vector_refresh()
                RETURNS trigger AS $$
                BEGIN
                    UPDATE resources_resource r SET
                        search_vector_en = resources_resource_compute_search_vector_en(
                            r.id, r.name_en, r.description_en, r.name_mi, r.description_mi),
                        search_vector_mi = resources_resource_compute_search_vector_mi(
                            r.id, r.name_en, r.description_en, r.name_mi, r.description_mi)
                    FROM resources_resource_tags m
                    WHERE m.resource_id = r.id
                      AND m.resourcetag_id = COALESCE(NEW.id, OLD.id);
                    RETURN NULL;
                END;
                $$ LANGUAGE plpgsql;

                -- Re-index every row from the correct columns into both vectors.
                UPDATE resources_resource SET name_en = name_en;
            """,
            reverse_sql="""
                -- Restore the 0015 single combined vector.
                DROP FUNCTION IF EXISTS resources_resource_compute_search_vector_en(bigint, text, text, text, text);
                DROP FUNCTION IF EXISTS resources_resource_compute_search_vector_mi(bigint, text, text, text, text);

                CREATE OR REPLACE FUNCTION resources_resource_compute_search_vector(
                    p_id bigint,
                    p_name_en text,
                    p_description_en text,
                    p_name_mi text DEFAULT '',
                    p_description_mi text DEFAULT ''
                ) RETURNS tsvector AS $$
                    SELECT
                        setweight(to_tsvector('english', COALESCE(p_name_en, '')), 'A')
                        || setweight(to_tsvector('english', COALESCE(p_description_en, '')), 'B')
                        || setweight(to_tsvector('simple',  COALESCE(p_name_mi, '')), 'A')
                        || setweight(to_tsvector('simple',  COALESCE(p_description_mi, '')), 'B')
                        || setweight(to_tsvector('english', COALESCE(
                            (SELECT string_agg(c.name_en, ' ')
                             FROM resources_resourcecomponent c
                             WHERE c.resource_id = p_id), '')), 'B')
                        || setweight(to_tsvector('simple', COALESCE(
                            (SELECT string_agg(c.name_mi, ' ')
                             FROM resources_resourcecomponent c
                             WHERE c.resource_id = p_id), '')), 'B')
                        || setweight(to_tsvector('english', COALESCE(
                            (SELECT string_agg(u.first_name || ' ' || u.last_name, ' ')
                             FROM users_user u
                             INNER JOIN resources_resource_author_users m
                                 ON m.user_id = u.id
                             WHERE m.resource_id = p_id), '')), 'C')
                        || setweight(to_tsvector('english', COALESCE(
                            (SELECT string_agg(e.name, ' ')
                             FROM entities_entity e
                             INNER JOIN resources_resource_author_entities m
                                 ON m.entity_id = e.id
                             WHERE m.resource_id = p_id), '')), 'C')
                        || setweight(to_tsvector('english', COALESCE(
                            (SELECT string_agg(t.name_en, ' ')
                             FROM resources_resourcetag t
                             INNER JOIN resources_resource_tags m
                                 ON m.resourcetag_id = t.id
                             WHERE m.resource_id = p_id), '')), 'C')
                        || setweight(to_tsvector('simple', COALESCE(
                            (SELECT string_agg(t.name_mi, ' ')
                             FROM resources_resourcetag t
                             INNER JOIN resources_resource_tags m
                                 ON m.resourcetag_id = t.id
                             WHERE m.resource_id = p_id), '')), 'C')
                        || setweight(to_tsvector('english', COALESCE(
                            (SELECT string_agg(t.abbreviation_en, ' ')
                             FROM resources_resourcetag t
                             INNER JOIN resources_resource_tags m
                                 ON m.resourcetag_id = t.id
                             WHERE m.resource_id = p_id), '')), 'C')
                        || setweight(to_tsvector('simple', COALESCE(
                            (SELECT string_agg(t.abbreviation_mi, ' ')
                             FROM resources_resourcetag t
                             INNER JOIN resources_resource_tags m
                                 ON m.resourcetag_id = t.id
                             WHERE m.resource_id = p_id), '')), 'C');
                $$ LANGUAGE sql;

                CREATE OR REPLACE FUNCTION resources_resource_search_vector_update()
                RETURNS trigger AS $$
                BEGIN
                    NEW.search_vector := resources_resource_compute_search_vector(
                        NEW.id, NEW.name_en, NEW.description_en,
                        NEW.name_mi, NEW.description_mi
                    );
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE OR REPLACE FUNCTION resources_resource_search_vector_refresh()
                RETURNS trigger AS $$
                BEGIN
                    UPDATE resources_resource SET search_vector =
                        resources_resource_compute_search_vector(
                            id, name_en, description_en, name_mi, description_mi
                        )
                    WHERE id = COALESCE(NEW.resource_id, OLD.resource_id);
                    RETURN NULL;
                END;
                $$ LANGUAGE plpgsql;

                CREATE OR REPLACE FUNCTION resources_resource_m2m_search_vector_refresh()
                RETURNS trigger AS $$
                BEGIN
                    UPDATE resources_resource SET search_vector =
                        resources_resource_compute_search_vector(
                            id, name_en, description_en, name_mi, description_mi
                        )
                    WHERE id = COALESCE(NEW.resource_id, OLD.resource_id);
                    RETURN NULL;
                END;
                $$ LANGUAGE plpgsql;

                CREATE OR REPLACE FUNCTION resources_resourcetag_search_vector_refresh()
                RETURNS trigger AS $$
                BEGIN
                    UPDATE resources_resource r
                    SET search_vector = resources_resource_compute_search_vector(
                        r.id, r.name_en, r.description_en, r.name_mi, r.description_mi
                    )
                    FROM resources_resource_tags m
                    WHERE m.resource_id = r.id
                      AND m.resourcetag_id = COALESCE(NEW.id, OLD.id);
                    RETURN NULL;
                END;
                $$ LANGUAGE plpgsql;

                UPDATE resources_resource SET name_en = name_en;
            """,
        ),
        migrations.RemoveIndex(
            model_name='resource',
            name='resources_r_search__82e125_gin',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='search_vector',
        ),
    ]
