# Generated by Django 5.2.16 on 2026-07-30 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0016_search_vector_per_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='resourcecomponent',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name='ResourceComponentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_viewed', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='resources.resourcecomponent')),
            ],
            options={
                'indexes': [models.Index(fields=['component', 'datetime_viewed'], name='resources_r_compone_f19fc8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResourceView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_viewed', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='resources.resource')),
            ],
            options={
                'indexes': [models.Index(fields=['resource', 'datetime_viewed'], name='resources_r_resourc_53a940_idx')],
            },
        ),
    ]
