# Generated by Django 5.2.16 on 2026-07-30 05:07

import ams.resources.utils
import ams.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0017_resource_view_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional image shown on the resource card and detail page.', storage=ams.users.models.get_public_media_storage, upload_to=ams.resources.utils.resource_thumbnail_path, verbose_name='thumbnail'),
        ),
    ]
