# Generated by Django 5.2.16 on 2026-07-30 05:11

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0018_resource_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecategory',
            name='base_colour',
            field=colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=25, samples=None, verbose_name='base colour'),
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='tag_style',
            field=models.CharField(choices=[('solid', 'Solid — filled badge'), ('outline', 'Outline — bordered badge'), ('soft', 'Soft — tinted background')], default='soft', max_length=10),
        ),
        migrations.AlterField(
            model_name='resourcetag',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='', help_text="Optional. Overrides the colour automatically derived from the category's base colour.", image_field=None, max_length=25, samples=None),
        ),
    ]
