# Generated by Django 5.2.16 on 2026-07-30 07:03

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0019_tag_colour_scheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcecategory',
            name='base_colour',
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='gradient_end_colour',
            field=colorfield.fields.ColorField(blank=True, default='', help_text='Colour for the last tag (by order). Leave blank to use the start colour for every tag.', image_field=None, max_length=25, samples=None, verbose_name='gradient end colour'),
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='gradient_start_colour',
            field=colorfield.fields.ColorField(blank=True, default='', help_text="Colour for the first tag (by order). Leave blank to disable automatic colouring for this category's tags.", image_field=None, max_length=25, samples=None, verbose_name='gradient start colour'),
        ),
        migrations.AlterField(
            model_name='resourcetag',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='', help_text="Optional. Overrides the colour automatically derived from the category's gradient.", image_field=None, max_length=25, samples=None),
        ),
    ]
