# Generated by Django 5.2.5 on 2025-10-19 00:30

import django.db.models.deletion
import relativedeltafield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_xeromutex_xerocontact'),
        ('organisations', '0002_alter_organisation_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('ORGANISATION', 'Organisation')], max_length=255)),
                ('duration', relativedeltafield.fields.RelativeDeltaField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'unique_together': {('name', 'type')},
            },
        ),
        migrations.CreateModel(
            name='IndividualMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('created_datetime', models.DateTimeField()),
                ('approved_datetime', models.DateTimeField(null=True)),
                ('cancelled_datetime', models.DateTimeField(null=True)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_memberships', to='billing.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_memberships', to=settings.AUTH_USER_MODEL)),
                ('membership_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_memberships', to='memberships.membershipoption')),
            ],
            options={
                'verbose_name': 'Membership: Individual',
                'verbose_name_plural': 'Membership: Individual',
            },
        ),
        migrations.CreateModel(
            name='OrganisationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('created_datetime', models.DateTimeField()),
                ('cancelled_datetime', models.DateTimeField(null=True)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisation_memberships', to='billing.invoice')),
                ('membership_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_memberships', to='memberships.membershipoption')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_memberships', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Membership: Organisation',
                'verbose_name_plural': 'Membership: Organisation',
            },
        ),
    ]
