# Generated by Django 5.2.5 on 2025-10-09 02:13

import relativedeltafield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('INDIVIDUAL', 'Individual')], max_length=255)),
                ('duration', relativedeltafield.fields.RelativeDeltaField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'unique_together': {('name', 'type')},
            },
        ),
    ]
