# Generated by Django 5.2.5 on 2025-10-19 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_xeromutex_xerocontact'),
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualmembership',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_memberships', to='billing.invoice'),
        ),
        migrations.AlterField(
            model_name='organisationmembership',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisation_memberships', to='billing.invoice'),
        ),
    ]
