# Generated by Django 5.2.5 on 2025-10-12 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('memberships', '0001_initial'),
        ('users', '0003_organisationtype_organisation_organisationmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipoption',
            name='type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('ORGANISATION', 'Organisation')], max_length=255),
        ),
        migrations.CreateModel(
            name='IndividualMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('created_datetime', models.DateTimeField()),
                ('approved_datetime', models.DateTimeField(null=True)),
                ('cancelled_datetime', models.DateTimeField(null=True)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_memberships', to='billing.invoice')),
                ('membership_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_memberships', to='memberships.membershipoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('created_datetime', models.DateTimeField()),
                ('cancelled_datetime', models.DateTimeField(null=True)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisation_memberships', to='billing.invoice')),
                ('membership_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_memberships', to='memberships.membershipoption')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_memberships', to='users.organisation')),
            ],
        ),
    ]
