# Generated by Django 5.2.5 on 2025-10-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_alter_individualmembership_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationmembership',
            name='approved_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
