# Generated by Django 5.2.8 on 2025-12-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_organisationmembership_approved_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipoption',
            name='invoice_reference',
            field=models.CharField(blank=True, help_text="What displays as the reference for any generated invoices. For example 'DTTA Membership'.", max_length=25),
        ),
    ]
