# Generated by Django 5.2.8 on 2025-12-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_membershipoption_invoice_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipoption',
            name='invoice_reference',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
