# Generated by Django 5.2.8 on 2025-12-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_alter_membershipoption_invoice_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipoption',
            name='archived',
            field=models.BooleanField(default=False, help_text='Mark as archived to prevent new signups'),
        ),
        migrations.AddField(
            model_name='membershipoption',
            name='max_seats',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Maximum number of seats for organisation memberships (optional limit)', max_digits=10, null=True),
        ),
    ]
