# Generated by Django 5.2.8 on 2026-01-01 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0006_membershipoption_archived_membershipoption_max_seats'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationmembership',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_memberships', to='organisations.organisation'),
        ),
    ]
