# Generated by Django 5.2.8 on 2026-01-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0007_alter_organisationmembership_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationmembership',
            name='max_seats',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Number of seats for this membership instance. Copied from membership option at creation and can be increased via seat top-ups.', max_digits=10, null=True),
        ),
    ]
