# Generated by Django 5.2.8 on 2026-01-04 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0009_add_organisationmembership_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationmembership',
            name='max_seats',
        ),
    ]
