# Generated by Django 5.2.8 on 2026-01-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0010_remove_organisationmembership_max_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualmembership',
            name='approved_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualmembership',
            name='cancelled_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisationmembership',
            name='approved_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisationmembership',
            name='cancelled_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
