# Generated by Django 5.2.8 on 2026-01-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0011_alter_individualmembership_approved_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipoption',
            name='voting_rights',
            field=models.BooleanField(default=True, help_text='Allow to vote in association matters.'),
        ),
    ]
