# Generated by Django 5.2.8 on 2026-01-05 02:05

from django.db import migrations


def copy_invoice_relationships_forward(apps, schema_editor):
    """Copy invoice relationships from memberships to invoices."""
    IndividualMembership = apps.get_model('memberships', 'IndividualMembership')
    OrganisationMembership = apps.get_model('memberships', 'OrganisationMembership')
    Invoice = apps.get_model('billing', 'Invoice')

    # Copy individual membership invoices
    for membership in IndividualMembership.objects.filter(invoice__isnull=False).iterator():
        Invoice.objects.filter(pk=membership.invoice_id).update(
            individual_membership_id=membership.pk
        )

    # Copy organisation membership invoices
    for membership in OrganisationMembership.objects.filter(invoice__isnull=False).iterator():
        Invoice.objects.filter(pk=membership.invoice_id).update(
            organisation_membership_id=membership.pk
        )


def copy_invoice_relationships_backward(apps, schema_editor):
    """Reverse the copy by setting invoice FK on memberships."""
    IndividualMembership = apps.get_model('memberships', 'IndividualMembership')
    OrganisationMembership = apps.get_model('memberships', 'OrganisationMembership')
    Invoice = apps.get_model('billing', 'Invoice')

    # Copy back to individual memberships
    for invoice in Invoice.objects.filter(individual_membership__isnull=False).iterator():
        IndividualMembership.objects.filter(pk=invoice.individual_membership_id).update(
            invoice_id=invoice.pk
        )

    # Copy back to organisation memberships
    for invoice in Invoice.objects.filter(organisation_membership__isnull=False).iterator():
        OrganisationMembership.objects.filter(pk=invoice.organisation_membership_id).update(
            invoice_id=invoice.pk
        )


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0012_membershipoption_voting_rights'),
        ('billing', '0007_invoice_individual_membership_and_more'),
    ]

    operations = [
        migrations.RunPython(
            copy_invoice_relationships_forward,
            reverse_code=copy_invoice_relationships_backward,
        ),
    ]
