# Generated by Django 5.2.8 on 2026-01-05 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0013_copy_invoice_relationships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualmembership',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='organisationmembership',
            name='invoice',
        ),
    ]
