# Generated by Django 5.2.8 on 2026-01-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0014_remove_individualmembership_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipoption',
            name='invoice_due_days',
            field=models.IntegerField(default=60, help_text='Number of days from invoice issue date until payment is due. This setting only affects new invoices created after changes are saved.'),
        ),
    ]
