# Generated by Django 5.2.8 on 2026-01-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0015_membershipoption_invoice_due_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipoption',
            name='max_charged_seats',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Maximum number of seats that will be charged (optional). If set, seats beyond this limit are free. Must be ≤ max_seats if both are set.', max_digits=10, null=True),
        ),
    ]
