# Generated by Django 5.2.8 on 2026-01-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0016_membershipoption_max_charged_seats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipoption',
            options={'ordering': ['order', 'cost']},
        ),
        migrations.AddField(
            model_name='membershipoption',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
    ]
