# Generated by Django 5.2.8 on 2026-01-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0017_alter_membershipoption_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipoption',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of this membership option shown to users when selecting. Keep concise for best display on pricing cards.'),
        ),
    ]
