# Generated by Django 5.2.8 on 2026-02-04 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0018_membershipoption_description'),
        ('organisations', '0006_organisationmember_idx_org_member_seats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='individualmembership',
            index=models.Index(fields=['user', 'approved_datetime', 'cancelled_datetime', 'start_date', 'expiry_date'], name='idx_indiv_mem_active'),
        ),
        migrations.AddIndex(
            model_name='organisationmembership',
            index=models.Index(fields=['organisation', 'approved_datetime', 'cancelled_datetime', 'start_date', 'expiry_date'], name='idx_org_mem_active'),
        ),
    ]
