# Generated by Django 5.2.15 on 2026-06-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0019_individualmembership_idx_indiv_mem_active_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membershipoption',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='membershipoption',
            name='description_en',
            field=models.TextField(blank=True, help_text='Optional description of this membership option shown to users when selecting. Keep concise for best display on pricing cards.', null=True),
        ),
        migrations.AddField(
            model_name='membershipoption',
            name='description_mi',
            field=models.TextField(blank=True, help_text='Optional description of this membership option shown to users when selecting. Keep concise for best display on pricing cards.', null=True),
        ),
        migrations.AddField(
            model_name='membershipoption',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membershipoption',
            name='name_mi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='membershipoption',
            unique_together={('name_en', 'type')},
        ),
    ]
