# Generated by Django 4.2.2 on 2023-06-26 03:19

from typing import Any

from django.db import migrations


def update_homepage_content(apps: Any, schema_editor: Any) -> None:
    HomePage = apps.get_model("base.HomePage")

    home_page = HomePage.objects.get(slug="home")
    home_page.heading = "Digital Technologies Teachers Aotearoa"
    home_page.registration_link_text = "Register for DTTA"
    home_page.body = (
        "The Digital Technologies Teachers Aotearoa is an association with the goal of advocating "
        "for our subjects. The aim of the association is to create a community of teachers where we can "
        "share resources, communicate and speak with one voice to get our subject area recognised "
        "and supported."
    )
    home_page.save()


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_create_homepage"),
    ]

    operations = [migrations.RunPython(update_homepage_content)]
