# Generated by Django 4.2.2 on 2023-06-26 03:19

from typing import Any

from django.db import migrations


def update_membership_page_content(apps: Any, schema_editor: Any) -> None:
    MembershipPage = apps.get_model("base.MembershipPage")

    membership_page = MembershipPage.objects.get(slug="membership")
    membership_page.body = (
        "<p>We would like to encourage you to join DTTA. We cater for all levels and mediums and offer support, "
        "events and resources to all digital technology teachers.</p>"
        "<p>Membership is free for primary and Māori medium kaiako as we grow how we support everyone.</p>"
        "<p>You can sign up either individually or for your organisation.  Please select:</p>"
    )
    membership_page.save()


class Migration(migrations.Migration):
    dependencies = [
        ("dtta", "0002_add_maori_locale"),
    ]

    operations = [migrations.RunPython(update_membership_page_content)]
