# Generated by Django 4.2.2 on 2023-06-26 03:19

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dtta", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="heading",
            field=models.CharField(blank=True, max_length=255, default="Digital Technologies Teachers Aotearoa"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="The Digital Technologies Teachers Aotearoa is an association with the goal of advocating "
                "for our subjects. The aim of the association is to create a community of teachers where we can "
                "share resources, communicate and speak with one voice to get our subject area recognised "
                "and supported.",
            ),
            preserve_default=False,
        ),
    ]
