# Generated by Django 4.2.2 on 2023-06-26 03:19

from typing import Any

from django.db import migrations


def update_homepage_page_headings(apps: Any, schema_editor: Any) -> None:
    HomePage = apps.get_model("base.HomePage")
    Locale = apps.get_model("wagtailcore.Locale")

    default_locale = Locale.objects.get(pk=1)

    home_page = HomePage.objects.get(slug="home", locale_id=default_locale.id)
    home_page.heading = "Digital Technologies"
    home_page.subheading = "Teachers Aotearoa"
    home_page.save()


class Migration(migrations.Migration):
    dependencies = [
        ("dtta", "0003_update_membership_page"),
        ("base", "0005_homepage_subheading"),
    ]

    operations = [migrations.RunPython(update_homepage_page_headings)]
