# Generated by Django 4.2.2 on 2023-06-26 03:19

from typing import Any

from django.db import migrations


def create_footer(apps: Any, schema_editor: Any) -> None:
    Footer = apps.get_model("base.Footer")
    Locale = apps.get_model("wagtailcore.Locale")

    default_locale = Locale.objects.get(pk=1)

    Footer.objects.create(
        site_logo_url="/static/images/logos/logo.png",
        street_address="",
        email_address="",
        middle_panel="",
        callout_heading="DTTA Membership",
        callout_text="We would like to encourage you to join DTTA. We cater for all levels and mediums and offer "
        "support, events and resources to all digital technology teachers.",
        callout_link_text="Learn more",
        callout_link_url="/membership/",
        locale_id=default_locale.id,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("dtta", "0004_custom_subheading"),
        ("base", "0008_footer"),
    ]

    operations = [migrations.RunPython(create_footer)]
