# Generated by Django 4.2.2 on 2023-06-26 03:19

from typing import Any

from django.db import migrations


def set_site_name(apps: Any, schema_editor: Any) -> None:
    Site = apps.get_model("wagtailcore.Site")

    site = Site.objects.get()

    site.site_name = "DTTA"
    site.save()


class Migration(migrations.Migration):
    dependencies = [
        ("dtta", "0005_footer_content"),
    ]

    operations = [migrations.RunPython(set_site_name)]
