# Generated by Django 5.2.8 on 2026-01-02 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('users', '0015_alter_organisationmember_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='organisation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='organisationmember',
            table=None,
        ),
    ]
