# Generated by Django 5.2.8 on 2026-01-02 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_alter_organisation_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organisationmember',
            name='unique_active_org_member',
        ),
        migrations.AddField(
            model_name='organisationmember',
            name='revoked_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddConstraint(
            model_name='organisationmember',
            constraint=models.UniqueConstraint(condition=models.Q(('declined_datetime__isnull', True), ('revoked_datetime__isnull', True)), fields=('user', 'organisation'), name='unique_active_org_member'),
        ),
    ]
