# Generated by Django 5.2.8 on 2026-01-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_remove_organisationmember_unique_active_org_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this organisation should be treated as active. Unselect this instead of deleting organisations.', verbose_name='active'),
        ),
    ]
