# Generated by Django 5.2.8 on 2026-01-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_organisation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationmember',
            name='last_sent_datetime',
            field=models.DateTimeField(help_text='Timestamp of when invite was last sent/resent', null=True),
        ),
    ]
