# Generated by Django 5.2.8 on 2026-02-04 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_organisationmember_last_sent_datetime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='organisationmember',
            index=models.Index(fields=['organisation', 'accepted_datetime', 'user'], name='idx_org_member_seats'),
        ),
    ]
