from django.urls import include, path

from .views import (
    AdminMembershipOptionListView,
    AdminOrganisationListView,
    AdminUserDetailView,
    AdminUserListView,
    AdminUserMembershipListView,
    OrganisationDetailView,
    UserDetailView,
    accept_organisation_user_invite,
    activate_user,
    add_user_membership,
    create_membership_option,
    create_organisation,
    edit_membership_option,
    edit_organisation,
    edit_user_profile,
    individual_registration,
    invite_organisation_member,
    register_organisation_member,
)

urlpatterns = [
    path("list/", AdminUserListView.as_view(), name="admin-user-list"),
    path("current/", UserDetailView.as_view(), name="current-user-view"),
    path("edit/<int:pk>/", edit_user_profile, name="edit-user-profile"),
    path("view/<int:pk>/", AdminUserDetailView.as_view(), name="admin-user-view"),
    path("add-membership/<int:pk>/", add_user_membership, name="add-user-membership"),
    path("memberships/", AdminUserMembershipListView.as_view(), name="admin-user-memberships"),
    path("membership-options/", AdminMembershipOptionListView.as_view(), name="admin-membership-options"),
    path("membership-options/create/", create_membership_option, name="create-membership-option"),
    path("membership-options/edit/<int:pk>/", edit_membership_option, name="edit-membership-option"),
    path("organisations/", AdminOrganisationListView.as_view(), name="admin-organisations"),
    path("organisations/create/", create_organisation, name="admin-create-organisation"),
    path("organisations/edit/<int:pk>/", edit_organisation, name="admin-edit-organisation"),
    path("organisations/view/<int:pk>/", OrganisationDetailView.as_view(), name="view-organisation"),
    path("organisations/invite/<int:pk>/", invite_organisation_member, name="invite-organisation-member"),
    path("accept-invite/<str:invite_token>/", accept_organisation_user_invite, name="accept-organisation-user-invite"),
    path("register-member/<str:invite_token>/", register_organisation_member, name="register-organisation-member"),
    path("individual-registration/", individual_registration, name="registration_register"),
    path("activate/<str:activation_key>/", activate_user, name="activate-user"),
    path("", include("registration.auth_urls")),
]
