#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py collectstatic --noinput

exec /usr/local/bin/gunicorn config.wsgi \
    --bind 0.0.0.0:5000 \
    --workers 2 \
    --threads 1 \
    --timeout 30
    --chdir=/app \
    --access-logfile - \
    --error-logfile - \
    --log-level info \
    --capture-output
