# Generated by Django 4.2.3 on 2023-08-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_create_emailconfirmationpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="subheading",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
