# Generated by Django 4.2.3 on 2023-08-16 02:01
from typing import Any

from django.db import migrations
from wagtail.models import Page


def create_main_menu(apps: Any, schema_editor: Any) -> None:
    MembershipPage = apps.get_model("base.MembershipPage")
    GenericPage = apps.get_model("base.GenericPage")
    ContentType = apps.get_model("contenttypes.ContentType")
    Locale = apps.get_model("wagtailcore.Locale")

    # Need to set show_in_menus to appear in menu
    MembershipPage.objects.filter(slug="membership").update(show_in_menus=True)
    content_type, __ = ContentType.objects.get_or_create(model="genericpage", app_label="base")

    default_locale = Locale.objects.get(pk=1)

    membership_page = Page.objects.get(slug="membership", locale_id=default_locale.id)

    # Need to set url_path or it doesn't show up in menu correctly
    membership_page.url_path = "/home/membership/"
    membership_page.live = True
    membership_page.save()

    about_page = GenericPage(
        locale_id=default_locale.id,
        title="About",
        heading="About",
        slug="about",
        url_path="/home/membership/about/",
        content_type=content_type,
        show_in_menus=True,
        live=True,
    )

    policies_page = GenericPage(
        locale_id=default_locale.id,
        title="Policies",
        heading="Policies",
        slug="policies",
        url_path="/home/membership/policies/",
        content_type=content_type,
        show_in_menus=True,
        live=True,
    )

    membership_page.add_child(instance=about_page)
    membership_page.add_child(instance=policies_page)

    Site = apps.get_model("wagtailcore.Site")
    MainMenu = apps.get_model("wagtailmenus.MainMenu")
    MainMenuItem = apps.get_model("wagtailmenus.MainMenuItem")

    site = Site.objects.get()

    # If there is already a main menu for this site, delete it
    MainMenu.objects.filter(site=site).delete()

    # Populate main menu
    main_menu = MainMenu.objects.create(site=site, max_levels=2)

    MainMenuItem.objects.create(menu=main_menu, link_text="Forum", link_url="#", allow_subnav=True, sort_order=0)
    MainMenuItem.objects.create(menu=main_menu, link_text="Resources", link_url="#", allow_subnav=True, sort_order=1)
    MainMenuItem.objects.create(menu=main_menu, link_text="Events", link_url="#", allow_subnav=True, sort_order=2)
    MainMenuItem.objects.create(menu=main_menu, link_page_id=membership_page.id, allow_subnav=True, sort_order=3)


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_add_generic_page"),
        ("wagtailsearch", "0007_delete_editorspick"),
        ("wagtailmenus", "0023_remove_use_specific"),
    ]

    operations = [
        migrations.RunPython(create_main_menu),
    ]
