# Generated by Django 4.2.3 on 2023-09-04 01:25

import uuid

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("base", "0007_add_main_menu"),
    ]

    operations = [
        migrations.CreateModel(
            name="Footer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("site_logo_url", models.CharField(max_length=255, blank=True)),
                ("street_address", wagtail.fields.RichTextField(blank=True)),
                ("email_address", models.CharField(max_length=255, blank=True)),
                ("middle_panel", wagtail.fields.RichTextField(blank=True)),
                ("callout_heading", models.CharField(max_length=255, blank=True)),
                ("callout_text", models.TextField(blank=True)),
                ("callout_link_text", wagtail.fields.RichTextField(blank=True)),
                ("callout_link_url", models.CharField(max_length=255, blank=True)),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.locale",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
        ),
    ]
