# Generated by Django 4.2.5 on 2023-09-12 00:45

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_footer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footer",
            name="site_logo_url",
        ),
        migrations.AlterField(
            model_name="footer",
            name="callout_link_text",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="footer",
            name="callout_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
